### DISCUSSION TITLE
Inconsistent behaviour from conveyor belts

### DISCUSSION THREAD

**Discussion by xBounceIT** [wolveix/satisfactory-server#164] [General]
**Describe the Bug**
It is probably a GAME bug and not an issue related to the server hosting, but i was wondering if any of other users of this image has been experiencing inconsistent begavior from convejor belts. 

As you can see by the following image sometimes it gets stuck instead of flowing into stockage.
![20221227153347_1](https://user-images.githubusercontent.com/35002896/209681718-ed1230db-6195-49e5-9308-3faf47116a79.jpg)

Docker Compose File
````
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - 'config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
            - AUTPAUSE=true
            - AUTOSAVEONDISCONNECT=true
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 16G
            reservations:
              memory: 12G

volumes:
  config:
````

```
===== START ISSUE REPORT =====
OS:  Linux ddhomeserver 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
RAM: 7GB/15GB
HDD: 21GB/116GB (19% used)
===== END ISSUE REPORT =====
```
