### DISCUSSION TITLE
Dedicated server on akash network

### DISCUSSION THREAD

**Discussion by 31trainman** [wolveix/satisfactory-server#212] [Show and tell]
Iv gotten your docker container to run the on the akash network. Here is the sdl file i wrote 

```
---
version: "2.0"
services:
  satisfactory-server:
    image: wolveix/satisfactory-server
    expose:
      - port: 80
        as: 80
        to:
          - global: true
    params:
      storage:
        data:
          mount: /mnt/data
          readOnly: false
profiles:
  compute:
    satisfactory-server:
      resources:
        cpu:
          units: 14
        memory:
          size: 16GB
        storage:
          - size: 20GB
          - name: data
            size: 25GB
            attributes:
              persistent: true
              class: beta2
  placement:
    dcloud:
      pricing:
        satisfactory-server:
          denom: uakt
          amount: 1000
deployment:
  satisfactory-server:
    dcloud:
      profile: satisfactory-server
      count: 1
```
