### DISCUSSION TITLE
Unhandled Exception: SIGSEGV: invalid attempt to read memory at address

### DISCUSSION THREAD

**Discussion by eeeeb** [wolveix/satisfactory-server#234] [Q&A] [answered]
Hey, it seems I am running into a similar problem as mentioned here: https://github.com/wolveix/satisfactory-server/discussions/195
For me it is a read memory issue. 

I tried to set `SERVERIP=""`: [satisfactory-server-modded_logs-serverip_empty.txt](https://github.com/wolveix/satisfactory-server/files/14393130/satisfactory-server-modded_logs-serverip_empty.txt)

`SERVERIP=0.0.0.0`: [satisfactory-server-modded_logs-serverip_0000.txt](https://github.com/wolveix/satisfactory-server/files/14393129/satisfactory-server-modded_logs-serverip_0000.txt)

But in both cases I get the same error and the server crashes every 10-15min.

My docker compose content which I use in Portainer. 
```
version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server-modded'
    hostname: 'eeeebs satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    volumes:
      - /home/eeeeb/portainer_container_data/satisfactory-modded/config:/config
    env_file:
      - stack.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 30G
        reservations:
          memory: 20G
```

So far I only encountered the error when running mods.

---

I thought the issue might be related to one of the mods. I found a thread with the same issue on the mods discord server: https://discord.com/channels/850965794581512192/1208037942573006879. 
The developer says he is also not sure what causes the issue:
> Is known but currently no idea what’s happen there- also because on some Linux os run all fine..

> yeah there is not fix in the next time. since we can basically not figure out what exact and why its crash.
> looks like a outer is invalid what makes not sense tbh. 
> I suggest if you want to play in Dedi use a Windows Server.

According to him the issue only happens on some but not all Linux versions and not on windows. 

---

Another observation I made, the container uses around 12 GB of RAM. When I play vanilla or with mods, which seems a bit weird.
I would have thought running mods will use more RAM. 
Could there be a hidden memory limit somewhere?

But this observation could also mean nothing and just be a coincidence. 

---

I am not saying that the docker container is the issue, I am just trying to find out where the issue could be...
The issue could just be related to the mods used and as the whole dedicated server with mods is still very experimental.
