### DISCUSSION TITLE
I've setup a server and went through the server manager and I'm having encryption token issues.

### DISCUSSION THREAD

**Discussion by hurricane-src** [wolveix/satisfactory-server#271] [Q&A] [answered]
I've read both [the 1.0 workaround](https://github.com/wolveix/satisfactory-server/issues/260) and the [token encryption missing](https://github.com/wolveix/satisfactory-server/discussions/263) but the solution doesn't appear to work for me.

I've setup a server using.
```
docker run \
        --detach \
        --name=satisfactory-server \
        --hostname satisfactory-server \
        --restart unless-stopped \
        --volume /home/steam/satisfactory-server/config:/config \
        --env MAXPLAYERS=4 \
        --env PGID=5001 \
        --env PUID=5001 \
        --env ROOTLESS=false \
        --env STEAMBETA=false \
        --memory-reservation=4G \
        --memory 16G \
        --publish 7777:7777/udp \
        --publish 7777:7777/tcp \
        --publish 15000:15000/udp \
        --publish 15777:15777/udp \
        --net=host \
        wolveix/satisfactory-server:latest
``` 
As you can see, the command uses the workaround for the API 1.0 issue.

With that command, docker tells me that it's ignoring the ports but I was still able to setup the server using the server manager. (admin password, user password, started a game session)
I can also enter the game using the "join" button in the server manager.

I've been able to build something and see the world was persistent if I delete and build the server again using the same command: the server seems to be working.

But if I try to join the game using "Join game" -> "Join game directly" I get a "encryption token missing" message. Since I went trough the server manager, I thought it was a problem with the ports.

When I look at the ports I see:

```
udp   UNCONN 0      0                                                                                 0.0.0.0:7777             0.0.0.0:*    users:(("FactoryServer-L",pid=25476,fd=14))                                                                                                                       
udp   UNCONN 0      0                                                                                       *:7778                   *:*    users:(("FactoryServer-L",pid=25476,fd=15))                                                                                                                       
tcp   LISTEN 0      16                                                                                0.0.0.0:7777             0.0.0.0:*    users:(("FactoryServer-L",pid=25476,fd=12))                                                                                                                       
tcp   LISTEN 0      16                                                                                      *:51059                  *:*    users:(("FactoryServer-L",pid=25476,fd=13))
```
I've read I'm supposed to have 7777, 15000 and 15777 open so I've tried something else:

I've deleted the docker image and instead I did:
```
docker run \
        --detach \
        --name=satisfactory-server \
        --hostname satisfactory-server \
        --restart unless-stopped \
        --volume /home/steam/satisfactory-server/config:/config \
        --env MAXPLAYERS=4 \
        --env PGID=5001 \
        --env PUID=5001 \
        --env ROOTLESS=false \
        --env STEAMBETA=false \
        --memory-reservation=4G \
        --memory 16G \
        --publish 7777:7777/udp \
        --publish 7777:7777/tcp \
        --publish 15000:15000/udp \
        --publish 15777:15777/udp \
        wolveix/satisfactory-server:latest
```

I was hoping to be able to ignore the API 1.0 issue as the server was essentially "ready".
If I'm not mistaken, all appropriate ports are forwarded.

```
udp   UNCONN 0      0                                                                                 0.0.0.0:7777             0.0.0.0:*    users:(("docker-proxy",pid=24795,fd=4))                                                                                                                           
udp   UNCONN 0      0                                                                                 0.0.0.0:15000            0.0.0.0:*    users:(("docker-proxy",pid=24757,fd=4))                                                                                                                           
udp   UNCONN 0      0                                                                                 0.0.0.0:15777            0.0.0.0:*    users:(("docker-proxy",pid=24739,fd=4))                                                                                                                           
udp   UNCONN 0      0                                                                                    [::]:7777                [::]:*    users:(("docker-proxy",pid=24801,fd=4))                                                                                                                           
udp   UNCONN 0      0                                                                                    [::]:15000               [::]:*    users:(("docker-proxy",pid=24763,fd=4))                                                                                                                           
udp   UNCONN 0      0                                                                                    [::]:15777               [::]:*    users:(("docker-proxy",pid=24745,fd=4))                                                                                                                           
tcp   LISTEN 0      4096                                                                              0.0.0.0:7777             0.0.0.0:*    users:(("docker-proxy",pid=24776,fd=4))                                                                                                                           
tcp   LISTEN 0      4096                                                                                 [::]:7777                [::]:*    users:(("docker-proxy",pid=24782,fd=4))
```

Yet like this I still get "encryption token missing" errors. (Additionally to the "Connect to the server API" if I enter the server manager.)

I'm out of ideas.

What am I missing?

Thanks.

**Comment by wolveix** [comment]
You're getting the token issue _because_ you haven't opened the server in the server manager. Sounds like it's working as expected, unless I'm not understanding? Either way, this doesn't sound like an issue with the image, and you may want to consult the Satisfactory Discord server or the official Q&A site :)

**Reply by hurricane-src** [reply]
Thanks for your reply.

Unless I'm misunderstanding what "opened the server in the server manager" means, I'm stating that "I was able to setup the server using the server manager" and even that I joined the game through said server manager. So I believe I did.
I was thus assuming the token has been created and it's a network setup issue. (Hence docker probably)

I'm considering installing the server without docker for comparison and confirm (or not) that it's a docker related issue.

I should also mention that my server is a "real" server located in a computing center. There is no external modem/router issue to consider.

**Reply by wolveix** [reply, marked as answer]
@hurricane-src I've just pushed an updated version that fixes the underlying connection issues. Please download that and see if it makes a difference :)

**Reply by hurricane-src** [reply]
It works, thanks :)

**Comment by conorlmcbride** [comment]
I'm still getting _encryption token missing_ when using join game button on latest version. Several users have been able to join successfully with the server manager. I have opened the server manager and started a game, made changes, etc.
We get the error connecting locally via IP/hostname on my network and from the internet via IP & hostname.

I see from previous comments it's probably a server related issue, but I thought you might want to know the new fix for underlying connection issues you published did not work for my instance.

Here is my compose file.

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/tcp'
            - '7777:7777/udp'
            # - '15000:15000/tcp'
            - '15000:15000/udp'
            # - '15777:15777/tcp'
            - '15777:15777/udp'
        volumes:
            - './config:/config'
        environment:
            - MAXPLAYERS=6
            - PGID=1000
            - PUID=1000
            - ROOTLESS=false
            - STEAMBETA=false
            - AUTOPAUSE=true
            - NETWORKQUALITY=3
        restart: unless-stopped
        healthcheck:
          test: bash /healthcheck.sh
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 120s
        deploy:
          resources:
            limits:
              memory: 8G
            reservations:
              memory: 6G
```
