### DISCUSSION TITLE
Can access server via LAN but not outside

### DISCUSSION THREAD

**Discussion by Sinuouser** [wolveix/satisfactory-server#290] [Q&A] [answered]
Hi! Set up a server using docker compose on Ubuntu 22.04.5 LTS, using the following config:

```
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    network_mode: host
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - ROOTLESS='false'
      - STEAMBETA='false'
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 24G
        reservations:
          memory: 12G

```

Everything seems to work fine - the server starts, I can connect, but only inside of my own network. If I use external ip (or domain), it doesn't work.

I got port 7777 forwarded both for UDP and TCP
![routerport](https://github.com/user-attachments/assets/c8525bc2-84b3-4fc9-a4f6-03240a3c080f)

![satisfactoryservers](https://github.com/user-attachments/assets/a6bc8c09-d4d6-4799-902a-5cd2d3014ff5)
The top one is using my domain (using pihole as DNS so it returns my local IP), the second one is the public IP.

Would anyone have any idea what could be the issue?
Grateful for any help.

Also thanks a ton for putting so much work into stuff like this - it's what makes communities thrive.
