### DISCUSSION TITLE
Issues building and deconstructing

### DISCUSSION THREAD

**Discussion by dermetti** [wolveix/satisfactory-server#319] [Q&A] [answered]
Hi,

I run the container on a Linux VPS. Initially the server runs fine with 4 people on it. After about 24h we start seeing issues such as being unable to deconstruct or build items. After restarting the container the issues disappeared temporarily. I use docker compose:
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
        volumes:
            - '/srv/Configs/satisfactory/config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
            - AUTOPAUSE=false
            - AUTOSAVEINTERVAL=900
            - AUTOSAVENUM=3
            - DISABLESEASONALEVENTS=true

        labels:
            - "traefik.enable=false"
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 20G
            reservations:
              memory: 16G
```
Any suggestions? Thanks
