### ISSUE TITLE
Container stop when loading save

### ISSUE THREAD

**Issue by Melethainiel** [wolveix/satisfactory-server#115]
First of all, thank you for your work, it's awesome !

**Describe the Bug**
the container download all files, booti up the server, load the game and at the end of the load it crash and restart.
it end with this :
```
[2021.12.22-21.05.40:327][  0]LogGame: Warning: FGFoliageRemoval_513::Apply(), failed to remove 6 instances
[2021.12.22-21.05.40:332][  0]LogGame: Warning: FGFoliageRemoval_509::Apply(), failed to remove 8 instances
[2021.12.22-21.05.40:345][  0]LogGame: Warning: FGFoliageRemoval_489::Apply(), failed to remove 48 instances
[2021.12.22-21.05.40:355][  0]LogGame: Warning: FGFoliageRemoval_487::Apply(), failed to remove 13 instances
[2021.12.22-21.05.40:358][  0]LogStreaming: Display: ULevelStreaming::RequestLevel(/Game/FactoryGame/Map/GameLevel01/Cave_X5_Y3_DesertCanyon_6_01) is flushing async loading
[2021.12.22-21.05.40:379][  0]LogStreaming: Display: ULevelStreaming::RequestLevel(/Game/FactoryGame/Map/GameLevel01/Cave_X4_Y0_Crater_2_01) is flushing async loading
[2021.12.22-21.05.40:388][  0]LogStreaming: Display: ULevelStreaming::RequestLevel(/Game/FactoryGame/Map/GameLevel01/Cave_X4_Y0_EndlessNothing_01) is flushing async loading
[2021.12.22-21.05.40:391][  0]LogStreaming: Display: ULevelStreaming::RequestLevel(/Game/FactoryGame/Map/GameLevel01/Cave_X4_Y1_Beurs_01) is flushing async loading
[2021.12.22-21.05.40:394][  0]LogStreaming: Display: ULevelStreaming::RequestLevel(/Game/FactoryGame/Map/GameLevel01/Cave_X4_Y1_Crater_1_01) is flushing async loading
```
I tried to set SERVERIP with the local ip but I got the same result.

**Your Runtime Command or Docker Compose File**
I'm running the container from portainer with the default configuration from docker-compose exemple.
```
Debugging enabled (the container will exit after printing the debug info)

Printing environment variables:
declare -x AUTOPAUSE="true"
declare -x AUTOSAVEINTERVAL="300"
declare -x AUTOSAVENUM="3"
declare -x AUTOSAVEONDISCONNECT="true"
declare -x CRASHREPORT="true"
declare -x DEBUG="true"
declare -x DISABLESEASONALEVENTS="false"
declare -x GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved"
declare -x GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
declare -x HOME="/root"
declare -x HOMEDIR="/home/steam"
declare -x HOSTNAME="594421ce1a0e"
declare -x MAXPLAYERS="4"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PGID="1000"
declare -x PUID="1000"
declare -x PWD="/config"
declare -x SERVERBEACONPORT="15000"
declare -x SERVERGAMEPORT="7777"
declare -x SERVERIP="0.0.0.0"
declare -x SERVERQUERYPORT="15777"
declare -x SHLVL="1"
declare -x SKIPUPDATE="false"
declare -x STEAMAPPID="1690800"
declare -x STEAMBETA="false"
declare -x STEAMCMDDIR="/home/steam/steamcmd"
declare -x USER="steam"

Disk usage:
15/78GB (20%)
Current user:
uid=0(root) gid=0(root) groups=0(root)
Proposed user:
uid=1000(?) gid=1000(?) groups=1000(?)
Exiting...
```

**System Specs (please complete the following information):**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Additional Context**
the same save file running outside of docker is working fine.
[Borthers3.0_autosave_0.zip](https://github.com/wolveix/satisfactory-server/files/7765305/Borthers3.0_autosave_0.zip)

**Comment by wolveix** [comment]
Appreciate the kind words!

Please upload your **full** runtime command/compose file, as well as your full container log.

**Comment by Melethainiel** [comment]
Here is the docker-compose :
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/administrator/satisfactory:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=true
        restart: unless-stopped
```
And here are the logs
[_satisfactory-server_logs.txt](https://github.com/wolveix/satisfactory-server/files/7767909/_satisfactory-server_logs.txt)
