### ISSUE TITLE
Autosave not active as a default setting?

### ISSUE THREAD

**Issue by poldixd** [wolveix/satisfactory-server#116]
**Describe the Bug**
At first: thank you for your work!

So, I started the container (and a new game) with the following command: 

```
docker run -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1000 -e STEAMBETA=false -v /home/satisfactory/config:/config -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest
```

After four hours of gameplay with my friend we left the server and I saw, that no savegame was created. You wrote in the documentation, that the autosave is active as default.

Later I started the server with `docker-compose` and the following config and the autosave is now working. I added `AUTOSAVEINTERVAL`, `AUTOSAVENUM` and `AUTOSAVEONDISCONNECT` to the `docker-compose.yml`

```yml
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - './config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
            - AUTOSAVEINTERVAL=300
            - AUTOSAVENUM=9
            - AUTOSAVEONDISCONNECT=true
        restart: unless-stopped
```
