### ISSUE TITLE
Container exiting with code 132

### ISSUE THREAD

**Issue by einfachtorben** [wolveix/satisfactory-server#125]
**Describe the Bug**
I tried using this container, but the container exited with the code 132

**Your Runtime Command or Docker Compose File**
I tried it first with the docker-compose:
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'Hostname'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/USER/satisfactory/config:/config'
        environment:
            - MAXPLAYERS=7
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: unless-stopped
```

that didnt work, i also tried "normal" docker 
```
docker run -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=7 -e PGID=1000 -e PUID=1000 -e STEAMBETA=false -e SATISFACTORY_SERVER_STARTUP_ARGUMENTS="FactoryGame -log -NoSteamClient -unattended -multihome=0.0.0.0" -v /home/USER/satisfactory/config:/config -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest
```

**System Specs (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
