### ISSUE TITLE
Workaround for M1?

### ISSUE THREAD

**Issue by I2oy** [wolveix/satisfactory-server#128]
Hello there!

I was trying to start up a container using docker-compose  on an M1 Mac Mini. I managed get it partially going until the game install.

 ``` zsh
satisfactory-server  | Connecting anonymously to Steam Public...OK
satisfactory-server  | Waiting for client config...OK
satisfactory-server  | Waiting for user info...OK
satisfactory-server  | ERROR! Failed to install app '1690800' (Requires 64bit operating system)
```

This is my docker-compose setup:

```yaml
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - './Satisfactory/config:/config'
        environment:
            - MAXPLAYERS=4
            - PUID=501
            - PGID=20
            - STEAMBETA=false
            - CPU_MHZ=3200
        restart: unless-stopped
```

Is there a possible workaround with the OS?
