### ISSUE TITLE
Permission issue removing server files

### ISSUE THREAD

**Issue by Mechazawa** [wolveix/satisfactory-server#135]
**Describe the Bug**
A permission error occours when removing `/home/steam/.config/Epic/FactoryGame/Saved/SaveGames/server`

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
    game:
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - backups:/config/backups
            - saves:/config/saves
            - gamefiles:/config/gamefiles
            - extra:/config/extra
        environment:
            - MAXPLAYERS=8
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: unless-stopped
        entrypoint: bash /config/extra/server-start.sh

volumes:
  extra:
  saves:
  gamefiles:
  backups:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=172.16.1.101,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/volume1/volumes/satisfactory_avex_backups"
```
**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux server0 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU           E5645  @ 2.40GHz
RAM: 40GB/64GB
HDD: 272GB/472GB (58% used)
===== END ISSUE REPORT =====
```

**Additional Context**
I have modified the run script to not do `cp -a` and instead do `cp -R` because my backups folder using NFS to connect to my storage server. `cp -a` implies `--preserve=all` which isn't possible when copying to a filesystem that doesn't support unix permissions.

The console log is as follows:
```
{...}
Steam Console Client (c) Valve Corporation - version 1654574676
-- type 'quit' to exit --
Loading Steam API...OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1690800' already up to date.
rm: cannot remove '/home/steam/.config/Epic/FactoryGame/Saved/SaveGames/server': Permission denied
```

Removing the offending line gives me a new permission error

```ln: failed to create symbolic link '/home/steam/.config/Epic/FactoryGame/Saved/SaveGames/ServerSettings.15777': Permission denied```
