### ISSUE TITLE
Initial startup fails due to "sed: can't read /home/steam/Engine.ini: Permission denied"

### ISSUE THREAD

**Issue by rnd256** [wolveix/satisfactory-server#138]
**Describe the Bug**
When I start the docker container for the first time using the below docker compose file, the container logs the following and then exits:
```
Attaching to satisfactory-server
satisfactory-server    | Setting autosave number to 3
satisfactory-server    | Setting crash reporting to True
satisfactory-server    | sed: can't read /home/steam/Engine.ini: Permission denied
```

**Your Runtime Command or Docker Compose File**
```yaml
version: '3'

  services:
    satisfactory-server:
      container_name: satisfactory-server
      hostname: satisfactory-server
      image: wolveix/satisfactory-server:latest
      restart: unless-stopped
      ports:
        - 7777:7777/udp
        - 15000:15000/udp
        - 15777:15777/udp
      volumes:
        - ${HOME}/game-data/satisfactory-server:/config
      environment:
        - MAXPLAYERS=6
        - PUID=1000
        - PGID=1000
        - AUTOPAUSE=true  # Pause game when no player is connected.
        - AUTOSAVEINTERVAL=300  # Auto-save interval, in seconds. 5 mins * 60 s/min = 300s.
        - AUTOSAVENUM=5  # Number of rotating auto-save files.
        - AUTOSAVEONDISCONNECT=true  # Auto-save when last online player disconnects.
        - SKIPUPDATE=false  # Avoid updating the game on container start/restart.
        - STEAMBETA=false
      logging:
        options:
          max-size: 100m
```

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.
```
===== START ISSUE REPORT =====
OS:  Linux <censored> 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
RAM: 9GB/32GB
HDD: 83GB/115GB (76% used)
===== END ISSUE REPORT =====
```
