### ISSUE TITLE
Steam updates failing

### ISSUE THREAD

**Issue by MarkusKeck** [wolveix/satisfactory-server#141]
**Describe the Bug**
docker container starts but failes to download the game, after that it gets stuck

**Your Runtime Command or Docker Compose File**
The default docker-compose from dockerhub, also tried without volumes / mounts
```yml
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/path/to/config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: unless-stopped
````
        

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux Debian-98-stretch-64-minimal 4.9.0-18-amd64 #1 SMP Debian 4.9.303-1 (2022-03-07) x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
RAM: 52GB/64GB
HDD: 126GB/437GB (31% used)
===== END ISSUE REPORT =====
```

**Additional Context**
docker logs satisfactory-server
```
Setting autosave number to 3
Setting crash reporting to True
Setting max players to 4
Setting autosave interval to 300s
Setting disable seasonal events to 0
Setting network quality number to 3
Setting auto pause to True
Setting autosave on disconnect to True
Checking available space...288GB detected
Downloading the latest version of the game...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
[  0%] Checking for available updates...
Thread failed to initialize
src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
```
