### ISSUE TITLE
Folders are not created with docker-compose

### ISSUE THREAD

**Issue by Fernichter** [wolveix/satisfactory-server#142]
**Describe the Bug**
I´ve mounted a folder inside my docker-compose file but folders like /gamefiles or /backups are not created when starting the server or after shutting it down.

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - /root/docker/satisfactory_compose/config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=true
        restart: unless-stopped
```
