### ISSUE TITLE
Connection Timed Out

### ISSUE THREAD

**Issue by RuinedYourLife** [wolveix/satisfactory-server#146]
**Describe the Bug**
When I try to connect to the server through the in-game UI, I get timed out 5 out of 6 times.
(I still managed to get in-game a few times)

_(save is auto loaded or else the server crashes on world creation because of: `Navmesh bounds are too large!`)_

**Your Runtime Command or Docker Compose File**
```yml
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/ubuntu/satisfactory-server/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: unless-stopped
```

**System Specs:**
```
===== START ISSUE REPORT =====
OS:  Linux ruined 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 5 3600X 6-Core Processor
RAM: 24GB/32GB
HDD: 22GB/467GB (5% used)
===== END ISSUE REPORT =====
```

**Additional Context**
Error Log
https://hastebin.com/ubedulonis.md
