### ISSUE TITLE
Server refusing to start due to low memory - there should be a way to disable this check and here's why!

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [wolveix/satisfactory-server#147]
**Describe the Bug**
When trying to start the server, I am facing 

```
Checking available memory...10GB detected
You have less than the required 12GB minimum (10GB detected) of available RAM to run the game server.
```

It is true that according to `free `I only have 10GB RAM free:
```
               total        used        free      shared  buff/cache   available
Mem:            31Gi        20Gi       9.4Gi        35Mi       1.3Gi        10Gi
Swap:          8.0Gi       1.0Gi       7.0Gi
```

BUT! In fact, I have about 6GB of RAM use and about 14GB is being utilized as default ZFS filesystem cache that htop marks nicely as "cache" (color yellow):

![image](https://user-images.githubusercontent.com/24213618/192107080-dbb13431-e394-4a5f-8d4f-bf91f0e2386d.png)

The behavior of ZFS cache is very submissive: When there's free memory, it uses it, but processes have higher priority and take it easily. 

I believe a quick workaround for this would be a flag that overrides the error and turns it into a warning. 

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server-latest'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - './satisfactory-data:/config'
        environment:
            - MAXPLAYERS=8
            - PGID=1000
            - PUID=1000
            - AUTOSAVENUM=15
            - NETWORKQUALITY=3
            - STEAMBETA=false
            - AUTOPAUSE=false
            - SKIPUPDATE=false
        restart: unless-stopped
```

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.
```
===== START ISSUE REPORT =====
OS:  Linux data 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 5 2600 Six-Core Processor
RAM: 10GB/31GB
HDD: 194GB/468GB (44% used)
===== END ISSUE REPORT =====
```

**Additional Context**
Thanks a lot for making this docker image!

Besides the bugreport up there, I have another question, but doesn't worth opening another report:
Can you please add the "meaning" of networkquality to the readme files? I swear I looked everywhere, but I couldn't find. I assume 3 is the highest and 0 or 1 are the lowest, but I couldn't find info about it.
