### ISSUE TITLE
Rebuilding container got an error after today's update to the game

### ISSUE THREAD

**Issue by roope242** [wolveix/satisfactory-server#159]
**Describe the Bug**
Rebuilding container got an error after today's update to the game

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/roope/Docker/Satisfactory/config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 16G
            reservations:
              memory: 12G
```

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.
```
===== START ISSUE REPORT =====
OS:  Linux komerodebian 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
RAM: 6GB/15GB
HDD: 17GB/228GB (8% used)
===== END ISSUE REPORT =====
```

**Additional Context**
The docker container died, couldn't be removed with `docker compose down` or `docker rm -f` as they both ended up an error.  
Also an error ( `Error! App '1690800' state is 0x606 after update job.` ) happened before the container died.
