### ISSUE TITLE
environment variable for network quality is ignored or overwritten

### ISSUE THREAD

**Issue by iaxx** [wolveix/satisfactory-server#168]
**Describe the Bug**
Network Quality ignores Environment Variables set in the docker compose file. 

**Your Runtime Command or Docker Compose File**

```
version: '3.4'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - './data:/config'
        environment:
            - NETWORKQUALITY=3
            - MAXPLAYERS=10
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
            - AUTOSAVEINTERVAL=120
            - AUTOPAUSE=false
        restart: unless-stopped
```

**System Specs:**

```
===== START ISSUE REPORT =====
OS:  Linux gamedocker 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
CPU: AMD Ryzen 7 3800X 8-Core Processor
RAM: 5GB/20GB
HDD: 13GB/97GB (14% used)
===== END ISSUE REPORT =====
```

**Additional Context**
Launching the server and running FG.NetworkQuality in the console gives the result of 1 instead of 3 as set by the constructor. 

![image](https://user-images.githubusercontent.com/13745514/212982594-ae5b573a-ee71-4928-b851-972630684d44.png)
