### ISSUE TITLE
Server won't start anymore with latest image

### ISSUE THREAD

**Issue by shaguarger** [wolveix/satisfactory-server#18]
Hi @wolveix, thanks for the great work! 

Your Satisfactory image ran smooth until yesterday. After over 2 weeks my server won't start anymore. It crashed soon after I fell down and should have died, but didn't. I stopped the server, saw that you made 2 commits, pulled and started. Since then this happens:

```
satisfactory-server    | Checking available space...
satisfactory-server    | Downloading the latest version of the game...
satisfactory-server    | Redirecting stderr to '/root/.steam/logs/stderr.txt'
satisfactory-server    | Looks like steam didn't shutdown cleanly, scheduling immediate update check
satisfactory-server    | [  0%] Checking for available updates...
satisfactory-server    | [----] Verifying installation...
satisfactory-server    | Steam Console Client (c) Valve Corporation
satisfactory-server    | -- type 'quit' to exit --
satisfactory-server    | Loading Steam API...OK
satisfactory-server    | @sSteamCmdForcePlatformType windows
satisfactory-server    | "@sSteamCmdForcePlatformType" = "windows"
satisfactory-server    | Logging in user 'xxx' to Steam Public...OK
satisfactory-server    | Waiting for client config...OK
satisfactory-server    | Waiting for user info...OK
satisfactory-server    | force_install_dir /config/gamefiles
satisfactory-server    | app_update "526870"
satisfactory-server    | Success! App '526870' already up to date.
satisfactory-server    | quit
satisfactory-server    | /root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
```

I tried restarting and removing data. I ended up with only the savefile.sav and the docker-compose.yml

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            - STEAMUSER=xxx
            - STEAMPWD=yyy
            - STEAMCODE=zzz
            - MAXBACKUPS=100
        ports:
            - '7777:7777/udp'
        volumes:
            - './config:/config'
        restart: unless-stopped
```

Sadly there is only the `latest` tag so I can't check if it's an issue with the image.

Any ideas?

PS.: The savefile does load on another server with the latest image.

**Comment by wolveix** [comment]
Hey! Glad to hear that you're enjoying the project :) 

Hm, that looks like a SteamCMD issue. Try removing the container and re-creating it?

**Comment by shaguarger** [comment]
So I tried to remove everything without success. :|

```
rm -rf config/steam/* config/gamefiles/*
docker container prune
docker image prune --all
```

It printed out stuff, but nothing important:

```
satisfactory-server    | Work thread 'CHTTPClientThreadPool:1' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
satisfactory-server    | Work thread 'CHTTPClientThreadPool:0' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
satisfactory-server    | Work thread 'CHTTPClientThreadPool:2' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
satisfactory-server    | /root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
satisfactory-server    | Work thread 'CHTTPClientThreadPool:1' is marked esatisfactory-server exited with code 137
```

I checked `docker stats` for mem usage, but it won't use more then 20MB.

**Comment by wolveix** [comment]
You don't need to purge the image, you just need to stop and remove the current container. All mapped contents can stay as they are, too. Since you're using Docket Compose, the following should suffice:

```bash
docker-compose down
docker-compose up -d
docker logs satisfactory-server -f
```

**Comment by shaguarger** [comment]
I know. It was pure desperation. I tried a lot of up/down.

**Comment by wolveix** [comment]
Ah, okay. Could you provide the container's logs after the new container starts, please?

**Comment by shaguarger** [comment]
```
user@server:/opt/satisfactory# docker-compose down
Removing network satisfactory_default
WARNING: Network satisfactory_default not found.



user@server:/opt/satisfactory# docker-compose up -d
Creating network "satisfactory_default" with the default driver
Creating satisfactory-server ... done



user@server:/opt/satisfactory# docker logs satisfactory-server -f
Checking available space...
Downloading the latest version of the game...
Redirecting stderr to '/root/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK
@sSteamCmdForcePlatformType windows
"@sSteamCmdForcePlatformType" = "windows"
Logging in user 'steam_account' to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
force_install_dir /config/gamefiles
app_update "526870"
Success! App '526870' already up to date.
quit
/root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
```

**Comment by shaguarger** [comment]
So I added the Steam directories as volumes in the docker-compose.yml

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            - STEAMUSER=xxx
            - STEAMPWD=yyy
            - STEAMCODE=zzz
            - MAXBACKUPS=100
        ports:
            - '7777:7777/udp'
        volumes:
            - ./config:/config
            - ./steam:/root/.steam
            - ./logs:/root/Steam/logs
        restart: unless-stopped
```

Noting to find in the Steam logs.

**Comment by wolveix** [comment]
Yeah it's not related to any recent changes; this is a SteamCMD issue which I'm currently investigating. I'm unable to replicate the issue on my end (fresh install).

**Comment by wolveix** [comment]
I wonder if this is permissions-related, similarly to the issue experienced in #11. Could you try running the container without any bound directories?

**Comment by shaguarger** [comment]
Without any volumes, still no:

```
satisfactory-server    |  Update state (0x81) verifying update, progress: 94.46 (15930835827 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 95.51 (16108794509 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 96.58 (16289363193 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 97.63 (16466097269 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 98.67 (16640874479 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 99.71 (16816173408 / 16865339122)
satisfactory-server    | Success! App '526870' fully installed.
satisfactory-server    | quit
satisfactory-server    | /root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
```

**Comment by wolveix** [comment]
So just to confirm, you had no directory bindings either?

**Comment by shaguarger** [comment]
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        build: ./satisfactory-server
        environment:
            - STEAMUSER=xxx
            - STEAMPWD=yyy
            - STEAMCODE=zzz
            - MAXBACKUPS=100
        ports:
            - '7777:7777/udp'
        restart: unless-stopped
```

`docker-compose up` ran as root

I also tried another run with your latest just to be sure:

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            - STEAMUSER=xxx
            - STEAMPWD=yyy
            - STEAMCODE=zzz
            - MAXBACKUPS=100
        ports:
            - '7777:7777/udp'
        restart: unless-stopped
```

No success either:

```
satisfactory-server    |  Update state (0x81) verifying update, progress: 97.76 (16487647626 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 98.84 (16668956202 / 16865339122)
satisfactory-server    |  Update state (0x81) verifying update, progress: 99.92 (16851474362 / 16865339122)
satisfactory-server    | Work thread 'CContentUpdateContext::m_pCPUTh' is marked exited, but we could not immediately join prior to deleting -- proceeding without join
satisfactory-server    | Success! App '526870' fully installed.
satisfactory-server    | quit
satisfactory-server    | /root/.steam/steamcmd/steamcmd.sh: line 38:    16 Killed                  $DEBUGGER "$STEAMEXE" "$@"
satisfactory-server exited with code 137
```
