### ISSUE TITLE
ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory

### ISSUE THREAD

**Issue by wasnertobias** [wolveix/satisfactory-server#186]
I have just updated to the latest docker image using
```
sudo docker-compose pull
sudo docker-compose up -d
```

However after startup I ran into the following issue as seen in the logs.

Logs
```
sudo docker-compose logs
WARNING: Some services (satisfactory-server) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Attaching to satisfactory-server
satisfactory-server    | Checking available memory...20GB detected
satisfactory-server    | Setting autosave number to 5
satisfactory-server    | Setting crash reporting to True
satisfactory-server    | Setting max objects number to 2162688
satisfactory-server    | Setting max tick rate to 120
satisfactory-server    | Setting timeout number to 300
satisfactory-server    | Setting max players to 4
satisfactory-server    | Setting autosave interval to 300s
satisfactory-server    | Setting disable seasonal events to 0
satisfactory-server    | Setting network quality number to 3
satisfactory-server    | Setting auto pause to True
satisfactory-server    | Setting autosave on disconnect to True
satisfactory-server    | Experimental flag is set. Experimental will be downloaded instead of Early Access.
satisfactory-server    | Checking available storage...190GB detected
satisfactory-server    | Downloading the latest version of the game...
satisfactory-server    | ln: failed to create symbolic link '/home/steam/.steam/root': No such file or directory
satisfactory-server    | ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory
```

My docker-compose.yml in /home/xxx/satisfactory:
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/xxx/satisfactory/config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - STEAMBETA=true
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 16G
            reservations:
              memory: 12G
```
