### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by NatyveCoder** [wolveix/satisfactory-server#201]
**Describe the Bug**
The server fails to start

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/satisfactory/data:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1003
            - PUID=1003
            - STEAMBETA=false
            - MAXTICKRATE=60
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 12G
            reservations:
              memory: 8G
```           

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux satisfactory 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
RAM: 15GB/15GB
HDD: 22GB/98GB (24% used)
===== END ISSUE REPORT =====
```
**Additional Context**
I have tried running docker as root. Ideally I'd like to be able to run the container from a service account that I have set up that does not have sudoers permissions.  I have this script in the service accounts cronjob set to run @reboot
```
#!/bin/bash
cd /home/satisfactory
# Stop server it already running
docker-compose down
docker-compose pull
# Start server container in detached mode
docker-compose up -d
```

I have double checked and I am connected to the internet just fine. All ports are correctly forwarded to the server.

**Docker Log**
```
Checking available memory...15GB detected
Setting autosave number to 5
Setting crash reporting to True
Setting max objects number to 2162688
Setting max tick rate to 60
Setting timeout number to 30
Setting max players to 4
Setting autosave interval to 300s
Setting disable seasonal events to 0
Setting network quality number to 3
Setting auto pause to True
Setting autosave on disconnect to True
Checking available storage...71GB detected
Downloading the latest version of the game...
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
httpclient.cpp (82) : Assertion Failed: Can't use HTTPS because steamcommon was compiled without ENABLE_OPENSSLCONNECTION
SteamUpdater: Error: Download failed: http error 0
[  0%] Download Complete.
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] Checking for available update...
httpclient.cpp (82) : Assertion Failed: Can't use HTTPS because steamcommon was compiled without ENABLE_OPENSSLCONNECTION
SteamUpdater: Error: Download failed: http error 0
[  0%] Download Complete.
SteamUpdater: Error: Steam needs to be online to update.  Please confirm your network connection and try again.
[  0%] !!! Fatal Error: Steam needs to be online to update.  Please confirm your network connection and try again.
```
