### ISSUE TITLE
Dual Stack Support for IPv4 and IPv6 inside the Container - Remove multihome parameter 

### ISSUE THREAD

**Issue by alcmaeo** [wolveix/satisfactory-server#202]
**Describe the Bug**
Connections from IPv6 only Clients are not possible without breaking IPv4 connections, if the container itself has both addresses (IPv4 + IPv6). 
In this scenario the parameter "-multihome" is a problem, because the server binds to only one of both adresses. In my case my host machine has a native IPv6 and a native IPv4 assigned. All container have a IPv4 and IPv6 address for the internal docker network. The docker proxy opens a proxy for Host-IPv6 to Container-IPv6 and Host-IPv4 to Container-IPv4. If you now define the multihome parameter, the dedicated server is only bound to one of them and all clients from the other stack can't connect to it. In the default config all clients over IPv4 have no problems and all clients over IPv6 can't connect. 

**Your Runtime Command or Docker Compose File**
```
version: "3"

services:
  satisfactory-server:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory-server
    hostname: satisfactory-server
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G
    restart: "no"
    networks:
      docker-intern:
        ipv4_address: 1.2.3.4
        ipv6_address: fd00::4 
    volumes:
      - satisfactory-data:/config
    ports:
      - "7777:7777/udp"  
      - "15000:15000/udp" 
      - "15777:15777/udp" 
    env_file:
      - satisfactory-server.env
```

satisfactotry-server.env:
```
# satisfactory-server Environment
TZ="Europe/Berlin"              # Timezone for Container
PUID=1000                       # Default PUID
PGID=1000                       # Default PGID
SERVERIP=""                     # explicitly set to empty value
SERVERGAMEPORT=7777             # default game's port
SERVERBEACONPORT=15000          # default game's beacon port
SERVERQUERYPORT=15777           # default game's query port
```

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Ubuntu 22.04.3 LTS (Kernel: 6.2.0-26-generic, Arch: x86_64)
CPU: AMD Ryzen 5 PRO 4650GE
RAM: 28GB/31GB
HDD: 121GB/456GB (28% used)
===== END ISSUE REPORT =====
```

**Additonal Context**
If the multihome Parater is not set, the satisfactory server is binding the ports for all ethernet devices / ip addresses. I'm currently running without any problems a manually modified container (with below described modifications) successfully. 

Change default value for SERVERIP in Dockerfile  to empty (in my case i set it to empty via the env file):
```
SERVERIP="" 
```

Check if the paramer SERVERIP is set in run.sh script and set the multihome parameter only if SERVERIP has a value. With empty value, the parameter is missing completely .
```
MULTIHOME_PARAMS=""
if [[ -n "${SERVERIP}" ]]; then
        MULTIHOME_PARAMS="-multihome=${SERVERIP}"
fi

exec ./FactoryServer.sh -log -NoSteamClient -unattended ?listen -Port="$SERVERGAMEPORT" -BeaconPort="$SERVERBEACONPORT" -ServerQueryPort="$SERVERQUERYPORT" ${MULTIHOME_PARAMS} "$@"
```

It would be great, if you can fix that, so i have not to modify the containers or build a own image for it. 

Thank you for your slim, clean and simple container for this game!
