### ISSUE TITLE
Illegal instruction (core dumped) when trying to start

### ISSUE THREAD

**Issue by jdbecker** [wolveix/satisfactory-server#215]
**Describe the Bug**
When running `docker-compose up` the container fails and exits with code 132 right after `Success! App '1690800' fully installed.`. The last message in the logs being `Illegal instruction (core dumped)`. My system's memory is a bit low, but still above what seems to be expected for Update 8 and I'm watching memory usage with `htop` and it never gets over even 1G.

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/jason/docker/satisfactory/config:/config'
        environment:
            - MAXPLAYERS=8
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: no
        deploy:
          resources:
            limits:
              memory: 6G
            reservations:
              memory: 4G
```

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====                                                                                            
OS:  Linux jason-ubuntu-server 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Phenom(tm) II X4 965 Processor                                                                                   
RAM: 7GB/7GB                                                                                                              
HDD: 14GB/456GB (4% used)                                                                                                 
===== END ISSUE REPORT =====                                                                                              
```

**Additional Context**
It's an old system that I only recently put back together with a fresh install of Ubuntu Server, so there shouldn't be anything else interfering, but the hardware is pretty dated. Still, I think it should all meet the minimum system requirements as of Update 8.

Thanks for any assistance!
