### ISSUE TITLE
Refusing to run with the root privileges - Aborted (core dumped)

### ISSUE THREAD

**Issue by fredrikscode** [wolveix/satisfactory-server#228]
**Describe the Bug**
Upon installing the server it'll come right to the end, "Success! App '1690800' fully installed.", then:
```
2023-12-26T19:29:40.978812100Z Success! App '1690800' fully installed.
2023-12-26T19:29:41.817764190Z Refusing to run with the root privileges.
2023-12-26T19:29:41.817823286Z libc++abi: __cxa_guard_acquire detected recursive initialization
2023-12-26T19:29:43.026621866Z Aborted (core dumped)
```

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
  server:
    image: 'wolveix/satisfactory-server:latest'
    volumes:
      - /mnt/gluster/games/satisfactory/config:/config
    environment:
        SERVERGAMEPORT: "7777"
        SERVERBEACONPORT: "15000"
        SERVERQUERYPORT: "15777"
        MAXPLAYERS: "4"
        PGID: "1000"
        PUID: "1000"
        ROOTLESS: "true"
        STEAMBETA: "false"
        AUTOPAUSE: "true"
        AUTOSAVEINTERVAL: "300"
        AUTOSAVENUM: "5"
        AUTOSAVEONDISCONNECT: "true"
        SKIPUPDATE: "false"
    restart: unless-stopped
    deploy:
      placement:
        constraints: [node.id == swarm-worker-01]
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.constraint-label=traefik
        # Game port
        - traefik.udp.routers.satisfactory.entrypoints=udp7777
        - traefik.udp.services.satisfactory.loadbalancer.server.port=7777
        # Beacon port
        - traefik.udp.routers.satisfactory.entrypoints=udp15000
        - traefik.udp.services.satisfactory.loadbalancer.server.port=15000
        # Query port
        - traefik.udp.routers.satisfactory.entrypoints=udp15777
        - traefik.udp.services.satisfactory.loadbalancer.server.port=15777
```

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux swarm-worker-01 5.14.0-362.8.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 7 14:54:22 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
RAM: 16GB (more or less dedicated to Satisfactory but I've limited the container to 12G at the moment)
HDD: Not represented well because of cluster storage. About 200GB dedicated for Satisfactory.
===== END ISSUE REPORT =====
```
Just in case it's not clear I'm running AlmaLinux (SELinux enabled)

**Additional Context**
Docker runs everything as user 1000 on my servers and I would appreciate being able to run this as rootless as well

**Comment by wolveix** [comment]
Hey. I'm unfamiliar with that error in particular. Could you try applying the `user` directive in your Compose file in addition to what you already have?

**Comment by Chaoschaot232** [comment]
Have had the same problem, even with a different user set within the ENV's.
Only runable as long as root privileges are given.

Is there a way to add a few debug break points into the code which we could enable to log stuff and send it over to you?

**Comment by wolveix** [comment]
@Chaoschaot232 yeah, I'm not surprised to hear it. Could you fill out the issue template, please? It doesn't need to be in a new issue, I just need to know your current system environment, as well as your Docker Compose/run command

**Comment by Chaoschaot232** [comment]
> @Chaoschaot232 yeah, I'm not surprised to hear it. Could you fill out the issue template, please? It doesn't need to be in a new issue, I just need to know your current system environment, as well as your Docker Compose/run command

Sure, give me a moment and I am collecting everything you need :)

**Comment by wolveix** [comment]
@Chaoschaot232 thanks! Could you try adding the `user` directive to your Docker Compose declaration for your corresponding user (for `1006`)?

**Comment by Chaoschaot232** [comment]
> @Chaoschaot232 thanks! Could you try adding the `user` directive to your Docker Compose declaration for your corresponding user (for `1006`)?

you mean smth like `- USER=satisfactory` right? So the name of the user behind my ID 1006.

**Comment by wolveix** [comment]
@Chaoschaot232 no, it'd be using the user directive, rather than as an array item. Please see this Stack Overflow link :) 

https://stackoverflow.com/questions/48727548/how-to-configure-docker-compose-yml-to-up-a-container-as-root

Your Compose should look something like this:

```
version: '3'

services:
  sf-server:
    container_name: sf-server
    restart: unless-stopped
    image: 'wolveix/satisfactory-server:latest'
    ports:
    - 15000:15000/udp
    - 7777:7777/udp
    - 15777:15777/udp
    volumes:
    - /home/data/marcel-gameserver/satisfactory/sf-micro:/config
    environment:
    - MAXPLAYERS=4
    - PGID=1006
    - PUID=1006
    - ROOTLESS=true
    - STEAMBETA=false
    - MAXOBJECTS=3000000
    user: YOUR_USERNAME_HERE
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G 
```
