### ISSUE TITLE
Unable to change server from private to friends only

### ISSUE THREAD

**Issue by mariusberget92** [wolveix/satisfactory-server#229]
**Describe the Bug**
When in-game and I try to change the session from private to friends only, it just changes back to private once i exit the menu.

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - 7777:7777/udp
      - 15000:15000/udp
      - 15777:15777/udp
    volumes:
      - '/home/anoneemo/docker/gameservers/satisfactory:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
```

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux anoneemo-ubuntu 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
RAM: 11GB/15GB
HDD: 149GB/457GB (35% used)
===== END ISSUE REPORT =====
```

**Additional Context**
Checked the configuration files i could find (ServerSettings.ini Game.ini Engine.ini etc.) but cannot find anywhere to change it manually either. I might be missing something. Port forwarding is done correctly and I can join my game, but no one else can, i also cannot copy the session ID because the session is private and i cannot change it.
