### ISSUE TITLE
Refusing to start with `PUID=0` (root) 

### ISSUE THREAD

**Issue by Mqxx** [wolveix/satisfactory-server#230]
**Describe the Bug**
An error occurs when starting the Docker container:

```
ERROR: PUID/user cannot be 0 (root)
```

Then the container restarts again and again

**Your Runtime Command or Docker Compose File**
```yml
version: '3'

services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'

    volumes:
      - './data:/config'
    
    environment:
      - MAXPLAYERS=10
      - PGID=1003
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    
    restart: always
    deploy:
      resources:
        limits:
          memory: 8G
    
        reservations:
          memory: 4G
```

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux loat-network-server 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 5 3400G with Radeon Vega Graphics
RAM: 5GB/13GB
HDD: 20GB/229GB (10% used)
===== END ISSUE REPORT =====
```

**Additional Context**
If I use `PUID=1000` (my normal user) as ID then the container starts without problems. However, I would like to run the whole thing as `root`.
