### ISSUE TITLE
Game binary missing

### ISSUE THREAD

**Issue by kicker69101** [wolveix/satisfactory-server#245]
**Describe the Bug**
Game fails to launch:
```
 Update state (0x5) verifying install, progress: 94.53 (4879406402 / 5161923338)
Success! App '1690800' fully installed.
Game binary is missing.
```

**Your Runtime Command or Docker Compose File**
```
  satisfactory-server:
      container_name: 'satisfactory-server'
      hostname: 'satisfactory-server'
      image: 'wolveix/satisfactory-server:latest'
      ports:
          - '7777:7777/udp'
          - '15000:15000/udp'
          - '15777:15777/udp'
      volumes:
          - '/<path>/satisfactory:/config'
      environment:
          - MAXPLAYERS=4
          - PGID=1000
          - PUID=1000
          - ROOTLESS=false
          - STEAMBETA=false
      restart: unless-stopped
```

**System Specs (please complete the following information):**

```
OS:  Linux <snip> 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 5 2600X Six-Core Processor
RAM: 32GB
HDD: 7T
```
