### ISSUE TITLE
Unable To Reach Server

### ISSUE THREAD

**Issue by jpcapone** [wolveix/satisfactory-server#248]
**Describe the Bug**

**Your Runtime Command or Docker Compose File**
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/var/lib/docker/volumes/satisfactory/config:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - ROOTLESS=false
            - STEAMBETA=false
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 6G
            reservations:
              memory: 4G
```

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.
```
===== START ISSUE REPORT =====
OS:  Linux craftmines 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
CPU: QEMU Virtual CPU version 2.5+
BIOS pc-i440fx-7.2  CPU @ 2.0GHz
RAM: 18GB/24GB
HDD: 97GB/192GB (54% used)
===== END ISSUE REPORT =====
```
**Additional Context**
I want to point out that i am using 15777 as the port as its the default port listed.  The server indicates that its listening on port 777 but when i use it:
![image](https://github.com/user-attachments/assets/94d8c345-ce52-48d7-9dc8-0b8c3dfc80e3)
I dont get the option to create game.  

the logs below are from a fresh docker deployment and the first connection to it.

https://pastebin.ai/8f0cfjidz5

 I am using the latest client version from Steam.
Also, I do not have any port forwarding on the firewall as i am assuming its not necessary for an internal connection?

Any suggestions would be appreciated!!!
