### ISSUE TITLE
app_update

### ISSUE THREAD

**Issue by skatilmi** [wolveix/satisfactory-server#252]
some assets are missing, In my case scanning for iron and steel ingots in conveyor belts.
How do to validate and repair the game files? It seems that satisfactory is not installed via the steamcmd

according to [https://steamdb.info/app/526870/info/](https://steamdb.info/app/526870/info/), the app id is 526870
```
app_update 526870 validate
```
gives:
```
ERROR! Failed to install app '526870' (No subscription)
```
My compose file:
```yml
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - 'D:/Games/SatisfactoryServer:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - ROOTLESS=false
            - STEAMBETA=false
            - AUTOSAVENUM=10
            - AUTOSAVEONDISCONNECT=true
            - AUTOPAUSE=false
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 12G
            reservations:
              memory: 12G
```
