### ISSUE TITLE
Encryption Token Missing

### ISSUE THREAD

**Issue by christianvw** [wolveix/satisfactory-server#265]
**Describe the Bug**

I get the the following error when joining the Satisfactory Server directly via IP address or domain. It doesn't make a difference whether I join directly on the local network (192.168.x.x) or via the internet.

Error in the Game UI:
````
Network Error: Encryption token missing
````

Error in the container logs:
````
[2024.09.10-16.03.15:159][528]LogNet: NotifyAcceptingConnection accepted from: 192.168.10.104:50628
[2024.09.10-16.03.15:192][529]LogNet: NotifyAcceptingConnection accepted from: 192.168.10.104:50628
[2024.09.10-16.03.15:192][529]LogNet: Server accepting post-challenge connection from: 192.168.10.104:50628
[2024.09.10-16.03.15:192][529]LogNet: IpConnection_2147482202 setting maximum channels to: 32767
[2024.09.10-16.03.15:193][529]PacketHandlerLog: Loaded PacketHandler component: DTLSHandlerComponent ()
[2024.09.10-16.03.15:193][529]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
[2024.09.10-16.03.15:194][529]LogNet: NotifyAcceptedConnection: Name: DedicatedserverEntry, TimeStamp: 09/10/24 16:03:15, [UNetConnection] RemoteAddr: 192.168.10.104:50628, Name: IpConnection_2147482202, Driver: GameNetDriver FGDSIpNetDriver_2147482293, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2024.09.10-16.03.15:194][529]LogNet: AddClientConnection: Added client connection: [UNetConnection] RemoteAddr: 192.168.10.104:50628, Name: IpConnection_2147482202, Driver: GameNetDriver FGDSIpNetDriver_2147482293, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2024.09.10-16.03.15:195][530]LogStreaming: Display: 0.001 ms for processing 12 objects in RemoveUnreachableObjects(Queued=0, Async=0). Removed 0 (1839->1839) packages and 0 (3289->3289) public exports.
[2024.09.10-16.03.15:226][530]LogNet: NotifyAcceptingChannel Control 0 server World /Game/FactoryGame/Map/DedicatedserverEntry.DedicatedserverEntry: Accepted
[2024.09.10-16.03.15:226][530]LogNet: Remote platform little endian=1
[2024.09.10-16.03.15:226][530]LogNet: This platform little endian=1
[2024.09.10-16.03.15:226][530]LogNet: Warning: IpConnection_2147482202: No EncryptionToken specified, disconnecting.
[2024.09.10-16.03.15:226][530]LogNet: UNetConnection::SendCloseReason:
[2024.09.10-16.03.15:226][530]LogNet:  - Result=EncryptionTokenMissing, ErrorContext="EncryptionTokenMissing"
[2024.09.10-16.03.15:226][530]LogNet: UNetConnection::Close: [UNetConnection] RemoteAddr: 192.168.10.104:50628, Name: IpConnection_2147482202, Driver: GameNetDriver FGDSIpNetDriver_2147482293, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID, Channels: 3, Time: 2024.09.10-16.03.15
[2024.09.10-16.03.15:226][530]LogNet: UNetConnection::SendCloseReason:
[2024.09.10-16.03.15:226][530]LogNet:  - Result=EncryptionTokenMissing, ErrorContext="EncryptionTokenMissing"
[2024.09.10-16.03.15:226][530]LogNet: UChannel::Close: Sending CloseBunch. ChIndex == 0. Name: [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 192.168.10.104:50628, Name: IpConnection_2147482202, Driver: GameNetDriver FGDSIpNetDriver_2147482293, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
[2024.09.10-16.03.15:260][531]LogNet: UNetConnection::PendingConnectionLost. [UNetConnection] RemoteAddr: 192.168.10.104:50628, Name: IpConnection_2147482202, Driver: GameNetDriver FGDSIpNetDriver_2147482293, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID bPendingDestroy=0 
[2024.09.10-16.03.15:260][531]LogNet: NotifyAcceptingConnection accepted from: 192.168.10.104:50628
[2024.09.10-16.03.15:260][531]LogNet: NotifyAcceptingConnection accepted from: 192.168.10.104:50628
[2024.09.10-16.06.36:182][507]LogNet: NotifyAcceptingConnection accepted from: 192.168.10.104:50686
[2024.09.10-16.06.36:216][508]LogNet: NotifyAcceptingConnection accepted from: 192.168.10.104:50686
[2024.09.10-16.06.36:216][508]LogNet: Server accepting post-challenge connection from: 192.168.10.104:50686
[2024.09.10-16.06.36:216][508]LogNet: IpConnection_2147482193 setting maximum channels to: 32767
````

**Docker Compose File**

````yml
version: '3'
services:
  prod-satisfactory-new:
    container_name: 'prod-satisfactory-new'
    hostname: 'prod-satisfactory-new'
    image: wolveix/satisfactory-server:v1.7.0
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/mnt/user/appdata/prod-satisfactory-new/config:/config'
    environment:
      - MAXPLAYERS=5
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
      - ROOTLESS=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G
    networks:
      br1.22:
        ipv4_address: 192.168.22.21

networks:
  br1.22:
    external: true
````

**System Specs (Server: Unraid):**

```
===== START ISSUE REPORT =====
OS:  Linux panda 6.1.79-Unraid #1 SMP PREEMPT_DYNAMIC Fri Mar 29 13:34:03 PDT 2024 x86_64 AMD Ryzen 7 5700G with Radeon Graphics AuthenticAMD GNU/Linux
CPU: AMD Ryzen 7 5700G with Radeon Graphics
BIOS AMD Ryzen 7 5700G with Radeon Graphics          Unknown CPU @ 3.8GHz
RAM: 56GB/60GB
HDD: 105GB/30GB (1% used)
===== END ISSUE REPORT =====
```

**Additional Context**

- Port Forwarding active for 7777 TCP and 7777 UDP (firewall allowed too)
- Satisfactory Client Version: CL#365306
- Satisfactory Server Version (this docker image): v1.7.0
- Fresh Install, no prior config or save files
