### ISSUE TITLE
On 1.0, restarting the docker container yields a "fresh" server despite being previously configured

### ISSUE THREAD

**Issue by natewalck** [wolveix/satisfactory-server#266]
**Describe the Bug**
I setup a fresh 1.0 server with no prior save files, used network mode of host to bypass the API issue we were seeing and configured a server as usual.

After configuring the server, setting admin pass, player pass, selecting a starting zone and generating it, I stopped/started the docker containe.

This yielded a "fresh" server where all configurations were gone. It behaved as if it had never been configured before (no name, no passwords set, etc).

**Docker Compose File**
Please censor anything sensitive. Your runtime command might look like this:

```shell
version: "3.5"
services:
    satisfactory:
        container_name: 'satisfactory'
        hostname: 'satisfactory'
        network_mode: host
        image: 'wolveix/satisfactory-server:latest'
        volumes:
            -  ${DOCKER_CONFIGS}/satisfactory/config:/config
        environment:
            - AUTOSAVEINTERVAL=300
            - AUTOSAVENUM=288
            - AUTOPAUSE=false
            - MAXPLAYERS=10
            - PUID=1000
            - PGID=999 # for the docker user
            - TZ=${TZ}
            - UMASK_SET=022 #optional
            - STEAMBETA=false
            - DISABLESEASONALEVENTS=true
        restart: unless-stopped
```

**Comment by LostAndDead** [comment]
I am having the same problem. None of the settings (passwords, save intervals) or even the game saves themselves are persisting through a restart here is my docker compose


```yml
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        network_mode: "host" 
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
        volumes:
            - '/root/apps/satisfactory:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1000
            - PUID=1000
            - ROOTLESS=false
            - STEAMBETA=false
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 12G
            reservations:
              memory: 4G
```

**Comment by alois-gaucher** [comment]
Same happening here

**Comment by Bethibande** [comment]
Same issue, data isn't being stored. Existing old saves also don't show up in the server.

**Comment by wolveix** [comment]
Yep, known issue, thank you all. I'll look into this shortly

**Comment by wolveix** [comment]
This should now be fixed. Make sure to `docker pull wolveix/satisfactory-server:latest`. Your image should then be `a74d21334805` (see below):

```
root@petaluma:/opt/games# docker images | grep satisf
wolveix/satisfactory-server           latest              a74d21334805   2 minutes ago       404MB
```

If you're still experiencing issues, please re-open! :)

**Comment by Panzer1119** [comment]
I think the problem is that the [Ubuntu 24 Docker image now contains a default user `ubuntu`](https://askubuntu.com/questions/1513927/ubuntu-24-04-docker-images-now-includes-user-ubuntu-with-uid-gid-1000) with the id `1000`.
So the user `steam` gets the id `1001` (instead of `1000`).

But the `run.sh` script is executed by default with the `PUID` and `PGID` env variables set to `1000`.

Changing them to `1001` should fix this?

**Comment by wolveix** [comment]
@Panzer1119 incredible, thanks for this! You're almost definitely 100% correct. I'll revisit this _after_ Coffee Stain fix the connectivity issue with 1.0

**Comment by putnam** [comment]
Can I ask why the downgrade from Ubuntu 24 to 18 in the Dockerfile?

**Comment by putnam** [comment]
Alright, breakdown here:

1. This repo's Dockerfile creates a `steam` user. That user ID is or should be considered unknown, but on a clean Ubuntu image it would be 1000 or, since 24.04, 1001, as it's the first available UID on the system.

2. At runtime this container switches to PUID/PGID provided in the environment, default 1000/1000. It also chown's all of the bind mount files to the assumed UID/GID, and then runs steamcmd -- but as $USER.

3. In init.sh, look at lines 62-74. Assume rootless is false (default). What happens here is you are modifying the steam user to have the uid specified by PUID, but you do not account for a potential collision. If there is already an account with that ID the usermod command will just fail, and there's nothing handling it here in this bash script. Because the Ubuntu 24.04 base image added a user at uid=1000, there is now a collision, and now the script will proceed with `steam` staying as uid=1001, $USER=steam, and then you modifying all the file permissions every time you start up (line 93) to be chown'd by uid=1000 (the default value of PUID).

**Comment by putnam** [comment]
Lots of ways to go about changing this but the simple path would be to just run steamcmd using the PUID provided. If you have a PUID provided at all, you run steamcmd with that, and if PUID is not provided, you run it as the steam user (and you chown the files using that steam user's ID). I think that would solve it in a way that is less likely to break in the future.

**Comment by wolveix** [comment]
@putnam is this also the case with Ubuntu 22.04?

**Comment by putnam** [comment]
As I reflect a little more on this I think $HOME won't be set properly if not run explicitly as the `steam` user. 

Like, let's say you provide PUID=55000. The Dockerfile made a steam user, it has UID 1001 (or whatever it may be), but it also has `HOME` set to /home/steam where all the files are expected to reside. But if you just run steamcmd with `gosu $PUID:PGID steamcmd` I think it would not behave correctly.

So it probably requires more work than that little change. I can poke around and send you a PR to save you some effort here. I was just doing a little static analysis.

**Comment by wolveix** [comment]
Yeah, I'd rebind $HOME I reckon. Great work! Looking forward to hopefully seeing a PR 👀

**Comment by christianvw** [comment]
🎉 For me it seems to work now with image `v1.7.3` (hash `d5e93211f497`) and this `docker-compose.yml` (network configuration because Unraid and macvlan):

<details>
  <summary>docker-compose.yml</summary>

````yml
version: '3'
services:
  prod-satisfactory-new:
    container_name: 'prod-satisfactory-new'
    hostname: 'prod-satisfactory-new'
    image: wolveix/satisfactory-server:v1.7.3
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/mnt/user/appdata/prod-satisfactory-new/config:/config'
    environment:
      - MAXPLAYERS=5
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
      - ROOTLESS=false
      - SERVERGAMEPORT=7777
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G
    networks:
      br1.22:
        ipv4_address: 192.168.22.21

networks:
  br1.22:
    external: true
````

</details>

After a stop and start of the container the save and settings are loaded correctly.

But the health endpoint of the container does not seem to work properly I think, it stated "Starting" all the time and then switched to "Unhealthy" after uploading a save.
