### ISSUE TITLE
The current user does not have write permissions for /config

### ISSUE THREAD

**Issue by themightylc** [wolveix/satisfactory-server#268]
The only thing the container shows in the log is

Checking available memory...19GB detected
The current user does not have write permissions for /config

my compose file:
services:
    satisfactory-server:
        container_name: 'satisfactory10'
        hostname: 'satisfactory10'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
        volumes:
            - '/srv/dev-disk-by-label-IronWolfA/SystemData/Satisfactory10:/config'
        environment:
            MAXPLAYERS: 4
            PGID: 998
            PUID: 997
            ROOTLESS: false
            STEAMBETA: false
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 16G
            reservations:
              memory: 12G

===== START ISSUE REPORT =====
OS:  Linux openmediavault.imagiro.net 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
RAM: 19GB/23GB
HDD: 78GB/285GB (29% used)
===== END ISSUE REPORT =====

I'm on portainer and I've triple-checked the userid, 
chowned to the right group and user and tried to 777 it

Other containers (including the previous version of this one) work.

**Comment by lennartdohmann** [comment]
Can you check the user permissions with `ls -lnd /srv/dev-disk-by-label-IronWolfA/SystemData/Satisfactory10` ?

**Comment by themightylc** [comment]
thank you for responding!

`drwxrwsrwx 3 997 998 4096 Sep 10 18:17 /srv/dev-disk-by-label-IronWolfA/SystemData/Satisfactory10`

**Comment by lennartdohmann** [comment]
You can add the shown user to ur compose:
```
services:
  your-service:
    image: your-image:latest
    user: "997:997"

```

**Comment by themightylc** [comment]
Zhanks. With that i get

```
Checking available memory...19GB detected
ERROR: Current user (997) is not root (0)
Pass your user and group to the container using the PGID and PUID environment variables
Do not use the --user flag (or user: field in Docker Compose) without setting ROOTLESS=true
```

When i set ROOTLESS to true I'm back at the same 
```
Checking available memory...19GB detected
The current user does not have write permissions for /config
```
:(

**Comment by wolveix** [comment]
Could be related to #254

**Comment by lennartdohmann** [comment]
Okay sorry can you try to Pass your user and group to the container using the PGID and PUID environment variables then?

**Comment by themightylc** [comment]
But isn't that what I'm doing?
```
services:
    satisfactory-server:
        container_name: 'satisfactory10'
        hostname: 'satisfactory10'
        image: 'wolveix/satisfactory-server:latest'
        user: "997:997"
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
        volumes:
            - '/srv/dev-disk-by-label-IronWolfA/SystemData/Satisfactory10:/config'
        environment:
            MAXPLAYERS: 4
            PGID: 998
            PUID: 997
            ROOTLESS: true
            STEAMBETA: false
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 16G
            reservations:
              memory: 12G
```
@wolveix  - if it is a issue with the system version, is it plausible that this was introduced by updating the container?
Will 1.0 run on an older version of the container?

Sorry man, I'm a software developer with 30 years experience, but linux (and thus docker) stuff just goes right above my head ;)
