### ISSUE TITLE
TCP Port is bound to 127.0.0.1 only

### ISSUE THREAD

**Issue by hexd0t** [wolveix/satisfactory-server#269]
**Describe the Bug**
When running the container with all stock options, the 1.0 server binds the TCP port to 127.0.0.1:7777, rejecting connections from outside the server (UDP Port works though, so I can see server ping, but cannot configure in server manager)

Using `nsenter` to run debug commands inside the network namespace of the container:

The TCP connections reach the container, but are rejected (reset TCP flag set) :
```bash
> tcpdump -nni eth0 tcp port 7777
19:00:43.287691 IP *CLIENTIP*.52295 > 172.20.0.2.7777: Flags [SEW], seq 3162542975, win 65535, options [mss 1412,nop,wscale 8,nop,nop,sackOK], length 0
19:00:43.287714 IP 172.20.0.2.7777 > *CLIENTIP*.52295: Flags [R.], seq 0, ack 3162542976, win 0, length 0
19:00:43.802488 IP *CLIENTIP*.52295 > 172.20.0.2.7777: Flags [S], seq 3162542975, win 65535, options [mss 1412,nop,wscale 8,nop,nop,sackOK], length 0
19:00:43.802512 IP 172.20.0.2.7777 > *CLIENTIP*.52295: Flags [R.], seq 0, ack 1, win 0, length 0
```

(172.20.0.2 is the private IP of the container)

Looking at the listening ports, the TCP socket is opened on 127.0.0.1:

```bash
ss -tulpn
Netid  State   Recv-Q  Send-Q   Local Address:Port    Peer Address:Port  Process
udp    UNCONN  0       0           127.0.0.11:36758        0.0.0.0:*      users:(("dockerd",pid=209240,fd=81))
udp    UNCONN  0       0              0.0.0.0:7777         0.0.0.0:*      users:(("FactoryServer-L",pid=210229,fd=13))
tcp    LISTEN  0       16           127.0.0.1:7777         0.0.0.0:*      users:(("FactoryServer-L",pid=210229,fd=12))
tcp    LISTEN  0       4096        127.0.0.11:46157        0.0.0.0:*      users:(("dockerd",pid=209240,fd=69))
```

**Docker Compose File**

```yaml
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './config:/config'
    environment:
      MAXPLAYERS: 4
      PGID: 1000
      PUID: 1000
      ROOTLESS: false
      STEAMBETA: false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 8G
```

**System Specs**

===== START ISSUE REPORT =====
OS:  Linux *hostname* 6.10.7-100.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 30 00:07:39 UTC 2024 x86_64 GNU/Linux
CPU: AMD EPYC 7702P 64-Core Processor
BIOS pc-i440fx-6.2  CPU @ 2.0GHz
RAM: 10GB/12GB
HDD: 40GB/50GB (80% used)
===== END ISSUE REPORT =====
