### ISSUE TITLE
Multiple reboot after a graceful shutdown

### ISSUE THREAD

**Issue by valentimarco** [wolveix/satisfactory-server#274]
**Describe the Bug**
Multiple reboot after a graceful shutdown. After 3 reboot, the server starts without issues
Fresh World on 1.0.

**Your Runtime Command or Docker Compose File**
```yaml
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        network_mode: host
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
        volumes:
            - '/mnt/giorgio/satisfactory-server:/config'
        environment:
            MAXPLAYERS: 4
            PGID: 1000
            PUID: 1000
            ROOTLESS: false
            STEAMBETA: false
            AUTOPAUSE: true
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 6G
            reservations:
              memory: 4G
```

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.

```shell
===== START ISSUE REPORT =====
OS:  Linux marco-ArchServer 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux
CPU: AMD Ryzen 5 2600 Six-Core Processor
RAM: 23GB/32GB
HDD: 69GB/100GB (73% used)
ZFS 1: 4GB/899GB (1% used) (Where the volume is mount)
===== END ISSUE REPORT =====
```

**Additional Context**
[issue.log](https://github.com/user-attachments/files/16955672/issue.log)
