### ISSUE TITLE
Kubernetes Connectivity Issue

### ISSUE THREAD

**Issue by Zblocker64** [wolveix/satisfactory-server#275]
**Describe the Bug**
1.0 API connector error

**Your Runtime Command or Docker Compose File**
Same as templates, but changed ports to 31000

**System Specs (please complete the following information):**

K8s Cluster. 3 control nodes, 4 worker nodes. Ubuntu 22.04

**Additional Context**

**Comment by Zblocker64** [comment]
```
[2024.09.10-22.13.51:021][  0]LogServer: Warning: Failed to bind Socket 'FGServerAPISocket' To Address '0.0.0.0:31000': SE_EADDRINUSE
[2024.09.10-22.13.51:021][  0]LogHttpListener: Warning: HttpListener unable to set desired buffer size (524288): Limited to 425984
[2024.09.10-22.13.51:021][  0]LogHttpListener: Created new HttpListener on 0.0.0.0:31000
[2024.09.10-22.13.51:022][  0]LogServer: Display: Server API listening on '0.0.0.0:31000' (Standalone)
[2024.09.10-22.13.51:022][  0]LogServer: Display: Server API listening on '[::]:31000' (Standalone)
[2024.09.10-22.13.51:023][  0]LogGame: MaxNumBackupsaves: 25
[2024.09.10-22.13.51:026][  0]LogLoad: Loading WwiseSoundEngine module: WwiseSoundEngine
[2024.09.10-22.13.51:026][  0]LogInit: Display: Game Engine Initialized.
[2024.09.10-22.13.51:026][  0]LogNetVersion: Set ProjectVersion to ++FactoryGame+rel-main-1.0.0-CL-365306. Version Checksum will be recalculated on next use.
[2024.09.10-22.13.51:033][  0]LogInit: OnPostEngineInit has been broadcasted successfully.
[2024.09.10-22.13.51:038][  0]LogInit: Display: Starting Game.
[2024.09.10-22.13.51:038][  0]LogNet: Browse: /Game/FactoryGame/Map/DedicatedserverEntry?name=Host?sessionName=SatisfactoryServer?Visibility=SV_FriendsOnly?loadgame=savefile?listen?bUseIpSockets
[2024.09.10-22.13.51:049][  0]LogLoad: LoadMap: /Game/FactoryGame/Map/DedicatedserverEntry?name=Host?sessionName=SatisfactoryServer?Visibility=SV_FriendsOnly?loadgame=savefile?listen?bUseIpSockets
[2024.09.10-22.13.51:049][  0]LogWorld: BeginTearingDown for /Temp/Untitled_0
[2024.09.10-22.13.51:049][  0]LogWorld: UWorld::CleanupWorld for Untitled, bSessionEnded=true, bCleanupResources=true
[2024.09.10-22.13.51:053][  0]LogStreaming: Display: 0.018 ms for processing 109 objects in RemoveUnreachableObjects(Queued=0, Async=0). Removed 20 (1270->1250) packages and 39 (1997->1958) public exports.
[2024.09.10-22.13.51:059][  0]LogUObjectHash: Compacting FUObjectHashTables data took   3.79ms
[2024.09.10-22.13.51:096][  0]LogChaos: FPhysicsSolverBase::AsyncDt:-1.000000
[2024.09.10-22.13.51:151][  0]LogAIModule: Creating AISystem for world DedicatedserverEntry
[2024.09.10-22.13.51:153][  0]LogLoad: Game class is 'BP_GameModeMenu_C'
[2024.09.10-22.13.51:158][  0]LogReplicationGraph: Display: SetActorDiscoveryBudget set to 20 kBps (5333 bits per network tick).
[2024.09.10-22.13.51:158][  0]LogNetCore: DDoS detection status: detection enabled: 0 analytics enabled: 0
[2024.09.10-22.13.51:158][  0]LogInit: BSD IPv4/6: Socket queue. Rx: 262144 (config 131072) Tx: 262144 (config 131072)
[2024.09.10-22.13.51:158][  0]LogInit: BSD IPv4/6: Socket queue. Rx: 262144 (config 131072) Tx: 262144 (config 131072)
[2024.09.10-22.13.51:158][  0]LogNet: Created socket for bind address: 0.0.0.0:0
[2024.09.10-22.13.51:159][  0]PacketHandlerLog: Loaded PacketHandler component: DTLSHandlerComponent ()
[2024.09.10-22.13.51:159][  0]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
[2024.09.10-22.13.51:159][  0]PacketHandlerLog: Loaded PacketHandler component: FactoryDedicatedServer.DSQueryHandlerComponentFactory (DSQueryHandlerComponent)
[2024.09.10-22.13.51:159][  0]LogNet: GameNetDriver FGDSIpNetDriver_2147482292 IpNetDriver listening on port 31000
[2024.09.10-22.13.51:159][  0]LogWorld: Bringing World /Game/FactoryGame/Map/DedicatedserverEntry.DedicatedserverEntry up for play (max tick rate 30) at 2024.09.10-22.13.51
[2024.09.10-22.13.51:193][  0]LogGame: Discovered 0 Remote Call Objects on AFGGameMode::InitGame
[2024.09.10-22.13.51:199][  0]LogWorld: Bringing up level for play took: 0.039493
[2024.09.10-22.13.51:199][  0]LogGameMode: Display: Match State Changed from EnteringMap to WaitingToStart
[2024.09.10-22.13.51:199][  0]LogGame: Apply Lightweight Instances from Load took: 0.000002 seconds
[2024.09.10-22.13.51:262][  0]LogGameState: Match State Changed from EnteringMap to WaitingToStart
[2024.09.10-22.13.51:262][  0]LogLoad: Took 0.213340 seconds to LoadMap(/Game/FactoryGame/Map/DedicatedserverEntry)
[2024.09.10-22.13.51:264][  0]LogGame: Telemetry, starting service.
[2024.09.10-22.13.51:264][  0]LogGame: Warning: Telemetry, no local player found.
[2024.09.10-22.13.51:266][  0]LogGame: Telemetry instance started without a platform.
[2024.09.10-22.13.51:283][  0]LogInit: Display: Engine is initialized. Leaving FEngineLoop::Init()
[2024.09.10-22.13.51:283][  0]LogLoad: (Engine Initialization) Total time: 4.28 seconds
[2024.09.10-22.13.51:318][  0]LogOnlineVoice: OSS: Voice interface disabled by config [OnlineSubsystem].bHasVoiceEnabled```

**Comment by wolveix** [comment]
Hey @Zblocker64! Could you provide your full log file, please? You can attach it rather than paste in the contents :) If you could also provide your config files, that'd be a huge help too!

**Comment by Zblocker64** [comment]
statefulset

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: satisfactory
spec:
  selector:
    matchLabels:
      app: satisfactory
  serviceName: "satisfactory"
  replicas: 1
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      containers:
      - name: satisfactory
        image: wolveix/satisfactory-server:latest
        env:
          - name: DEBUG
            value: "false"
          - name: MAXPLAYERS
            value: "8"
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          - name: SKIPUPDATE
            value: "false"
          - name: STEAMBETA
            value: "false"
          - name: SERVERGAMEPORT
            value: "31000"
        ports:
        - containerPort: 31000
          name: "gametcp"
          protocol: TCP
        - containerPort: 31000
          name: "game"
          protocol: UDP
        volumeMounts:
        - name: satisfactory-data
          mountPath: /config
  volumeClaimTemplates:
  - metadata:
      name: satisfactory-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
      storageClassName: beta3


```

Service

```
---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: satisfactory
spec:
  type: NodePort
  ports:
  - port: 31000
    nodePort: 31000
    protocol: UDP
    name: "game"
    targetPort: "game"
  - port: 31000
    nodePort: 31000
    protocol: TCP
    name: "gametcp"
    targetPort: "gametcp"
  selector:
    app: satisfactory




```

**Comment by Zblocker64** [comment]
[log.txt](https://github.com/user-attachments/files/16955750/log.txt)

**Comment by Zblocker64** [comment]
I have also verified that firewall is not an issue

**Comment by wolveix** [comment]
Hm, now this is interesting. And you're absolutely using the latest image? Could you try explicitly using the `1.7.3` tag instead of `latest`?

**Comment by Zblocker64** [comment]
positive. Checked checksum

```
Containers:
  satisfactory:
    Container ID:   containerd://90b71524252b2f6365684c6a360d8fce70a7fe1538ba39a5dd537f519459f33e
    Image:          wolveix/satisfactory-server:latest
    Image ID:       docker.io/wolveix/satisfactory-server@sha256:d5e93211f497369e90aa5404c268428f27c4e9db3485601a1b1265437fd02720
```

**Comment by Zblocker64** [comment]
trying with the image tag now

**Comment by Zblocker64** [comment]
I had this working last night before the update... using this port (31000) along with other ports.

**Comment by wolveix** [comment]
@Zblocker64 out of curiosity, what if you change it to 7777? I wonder if the game isn't rebinding properly

**Comment by Zblocker64** [comment]
You can't inside of k8s. Needs to be between 30000-32767

**Comment by Zblocker64** [comment]
I can try to make the internal 7777 and external 31000

**Comment by chadouming** [comment]
I have the same issue using port 7777 on podman, don't think the port itself is relevant. Since it is now using the same port but TCP and UDP, is it possible we are missing a /tcp or /udp somewhere ?

**Comment by EvilCeikor** [comment]
I have the same problem, I am using this on a QNAP with Docker and the following things I have tried:
- Default port via NAT
- Default port over the HOST network
- Default port via bridge
- custome ports with all network modes
- disable ipv6 in my network only ipv4
- disable ipv4 only ipv6

I think this is a coffee stain studios problem

**Comment by wolveix** [comment]
I'm confused, I believe you can absolutely bind to ports below 30000 on k8s, given that I've done so. I believe you need to use a LB or ingress, I forget.

But yes, even trying changing the port internally may help

**Comment by Zblocker64** [comment]
> I'm confused, I believe you can absolutely bind to ports below 30000 on k8s, given that I've done so. I believe you need to use a LB or ingress, I forget.
> 
> But yes, even trying changing the port internally may help

you can't if its a node port, with LB you can I believe

**Comment by Zblocker64** [comment]
Tried 31000 externally and 7777 internally and same issue

**Comment by chadouming** [comment]
Fixed my issue by making sure podman is using port 7777/udp and 7777/tcp, not just 7777 which I thought would bind to both protocol but doesn't seem so.

**Comment by wolveix** [comment]
Please avoid posting on this issue for anything that isn't a Kubernetes cluster (k8s). Other connectivity issues at this point are down to your environment (not being on the latest image, or not explicity allowing both 7777/tcp and 7777/udp per the README). You can track the dicsussion around those issues here: #260

**Comment by wolveix** [comment]
@Zblocker64 this is a difficult one. I wonder why it isn't binding? It's possible that Coffee Stains' permanent fix may make a difference here, I just struggle to see how given the dev's comments in Discord.

You're able to reach the server, and then you experience the API connectivity issue...have you tried with a fresh mounted directory? If not, please try that. Remove your existing PVC or similar and see whether it works without it

**Comment by Zblocker64** [comment]
I think the issue is the service.yaml isn't allowing tcp through right now.

```
satisfactory   NodePort    10.233.9.2   <none>        31000:31000/UDP   19h
```

**Comment by Nhlkoho** [comment]
> I have the same problem, I am using this on a QNAP with Docker and the following things I have tried:
> 
> * Default port via NAT
> * Default port over the HOST network
> * Default port via bridge
> * custome ports with all network modes
> * disable ipv6 in my network only ipv4
> * disable ipv4 only ipv6

I literally just got this working using docker on a qnap. Use bridge network and assign a static IP. Make sure you enable port forwarding for 7777 in your router for that IP. Everything else I left at default settings. I did create a satisfactory folder in my qnap home drive and bound that to /config on the storage tab when setting the environment vairables

**Comment by wolveix** [comment]
@Nhlkoho this is not the appropriate issue.

**Comment by Zblocker64** [comment]
> I think the issue is the service.yaml isn't allowing tcp through right now.
> 
> ```
> satisfactory   NodePort    10.233.9.2   <none>        31000:31000/UDP   19h
> ```

This was it, had to fully delete the `service.yaml` service and re apply it

**Comment by Zblocker64** [comment]
here is the updated `service.yaml` See adjusted `targetPort`

```
---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: satisfactory
spec:
  type: NodePort
  ports:
  - port: 31000
    nodePort: 31000
    protocol: UDP
    name: "game"
    targetPort: 31000
  - port: 31000
    nodePort: 31000
    protocol: TCP
    name: "gametcp"
    targetPort: 31000
  selector:
    app: satisfactory
```
