### ISSUE TITLE
Failed to Connect to the Server API

### ISSUE THREAD

**Issue by Newmcpe** [wolveix/satisfactory-server#286]
**Describe the Bug**
I have Failed to Connect to the Server API error after launching docker image in docker-compose

**Your Runtime Command or Docker Compose File**
```
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:v1.7.4'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
```

**System Specs (please complete the following information):**
===== START ISSUE REPORT =====
OS:  Linux dc01 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 5 3600 6-Core Processor
BIOS AMD Ryzen 5 3600 6-Core Processor               Unknown CPU @ 3.6GHz
RAM: 30GB/64GB
HDD: 309GB/436GB (75% used)
===== END ISSUE REPORT =====
