### ISSUE TITLE
Save game before upating the image 

### ISSUE THREAD

**Issue by Legonzaur** [wolveix/satisfactory-server#289]
**Describe the Bug**
I am using the image uploaded yesterday, which has the save saving bug.  Seen in #285 and #288

My server runs since yesterday, and we did play some couple of hours. 

I would like to be able to save save our game before anything happens. Right now, the save is most likely only the process ram, but if the server crashes or shutdowns for some reason, we'll lose all our progress

```yaml
satisfactory:
    image: wolveix/satisfactory-server:latest
    restart: unless-stopped
    volumes:
      - /opt/satisfactory:/config
    environment:
      MAXPLAYERS: 4
      PGID: 1000
      PUID: 1000
      ROOTLESS: false
      STEAMBETA: false
    network_mode: host
```

Here are the commands I tried to run on the save directory.
`chown -R 1000:1000 config_directory`
`chown -R 1001:1001 config_directory`
`chmod -R 777 config_directory`

Right now, the `config_directory/saved/server` folder is empty, even after trying all the previous commands, and waiting for an auto save.
