### ISSUE TITLE
Port forward on Fitzbox for both UDP and TCP

### ISSUE THREAD

**Issue by nkucza** [wolveix/satisfactory-server#293]
Hi,

my docker instance for the satisfactory server is planned to run on my NAS at home behind a fritz box.
As I just have realized, the ports are changed to be the same port (default 7777) for UDP as for TCP.

This is bad.. as far as I understand, I cannot forward the same port on my FritzBox 7590 for both types...
I know that that should usually work, as TCP and UDP are separate things, but the GUI won't let me.

My compose is below as a reference.
The `SERVERGAMEPORT` changes the port for both is that correct?
Any suggestions or help would be welcome!

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-exp-server'
        hostname: 'NilzWorld'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '6254:7777/udp'
            - '6255:7777/tcp'
        volumes:
            - '/homes/steam_games/satisfactory_exp:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1002
            - PUID=1002
        restart: unless-stopped
```
