### ISSUE TITLE
Automatic server restart not working?

### ISSUE THREAD

**Issue by iwa** [wolveix/satisfactory-server#294]
### Describe the Bug

I've been running your image for quite a long time now, so I was thrilled to finally update it to 1.0!
Launched a new fresh server after waiting for the issues around #260 to be fixed, and everything went smoothely

Only thing is, the server announced (in-game) its daily restart, but after the cooldown, nothing happened
I feel that is not the wanted behavior, right?

### Your Docker Compose File

```yaml
services:
  satisfactory-multi-v1:
    image: wolveix/satisfactory-server:latest
    container_name: satisfactory-multi-v1
    hostname: satisfactory-multi-v1
    restart: unless-stopped
    ports:
      - 7777:7777/tcp
      - 7777:7777/udp
    volumes:
      - /opt/docker/satisfactory-multi-v1/data/config:/config
    environment:
      - MAXPLAYERS=6
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 12G
networks: {}
```

### Debug Output

Had no output at that time, will try to catch news logs with debug option on

### System Specs (please complete the following information):

OS: Debian 12 - 6.1.106-3 (2024-08-26)
CPU: AMD Ryzen 9 5900HX
RAM: 20GB
HDD: 46GB/197GB (24% used)

### Logs

Don't have the logs when it happened, could attach when I'll be able to replicate
