### ISSUE TITLE
Server isn't open to public network

### ISSUE THREAD

**Issue by val-exe** [wolveix/satisfactory-server#296]
### Describe the Bug

I can't see or connect to my server using my public IP address. I can see the server and `curl -kv https://127.0.0.1:7777` works fine, but replacing it with my public IP always times out. Same situation within the Server Manager. 

At first I tried using just Docker Desktop to pull the image and create the container, and then I switched to cloning the repo and using docker-compose.

### Your Runtime Command or Docker Compose File

```yml
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './config:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=197609
      - PUID=197609
      - ROOTLESS='false'
      - STEAMBETA='false'
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
```

### Debug Output

```shell
Sorry, couldn't get this to work with docker-compose. (issue on my part)
```

### System Specs (please complete the following information):

OS:  Windows 11 (Docker Desktop on WSL 2)
CPU: AMD Ryzen 7 7800x3d
RAM: 16GB free out of 32GB
SSD: 373GB free out of 837GB

### Logs

[container-log.txt](https://github.com/user-attachments/files/16979165/container-log.txt)

### Additional Context

I've been following the issues yesterday trying to see if I can self-diagnose or fix my problem. I've tried every which way of port forwarding (including DMZ & turning firewalls off completely) and managed to make connections from my machine to the server. I also did it via docker's local network interface and that also worked. I haven't been able to test other computers on my LAN yet, but I'm also sure it's not an ISP issue since I am currently hosting other servers and discord bots, and I have hosted at least one instance of a satisfactory server for every major update since Update 5. (granted, this is the first time I decided to use docker for it)
