### ISSUE TITLE
1.0 container / server process not listening on IPv6

### ISSUE THREAD

**Issue by goofball222** [wolveix/satisfactory-server#301]
Not sure if this is a material change to the image, or something in the game server itself with 1.0. It appears the server process no longer listens internally on IPv6 regardless of the `SERVERIP` environment variable. This behavior continues even after the current 1.0 game hotfix and workaround removal from the image.

Exec'd into running container & ran `apt update && apt install net-tools` to provide access to netstat - 

```bash
root@satisfactory:/config# netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:7777            0.0.0.0:*               LISTEN
tcp        0      0 172.17.0.3:33712        35.227.230.186:443      ESTABLISHED
tcp        0      0 172.17.0.3:47608        104.26.12.205:443       ESTABLISHED
tcp6       0      0 :::44429                :::*                    LISTEN
tcp6       0      0 2607:XXXX:XXXX:XXXX::44786 2620:2d:4002:1::103:80  TIME_WAIT
tcp6       0      0 2607:XXXX:XXXX:XXXX::44792 2620:2d:4002:1::103:80  TIME_WAIT
tcp6       0      0 2607:XXXX:XXXX:XXXX::44792 2620:2d:4002:1::102:80  TIME_WAIT
udp        0      0 0.0.0.0:7777            0.0.0.0:*
udp6       0      0 :::7778                 :::*
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  3      [ ]         STREAM     CONNECTED     116566441
unix  3      [ ]         STREAM     CONNECTED     116566442
unix  3      [ ]         STREAM     CONNECTED     116561616
unix  3      [ ]         STREAM     CONNECTED     116561617
```

Container attached to docker default bridge network does have IPv6 connectivity and IPv6 global transit. IE: can `ping6 ipv6.google.com` if `inetutils-ping` is added to running container.

Current docker-compose.yml
```yaml
services:
  satisfactory:
    container_name: satisfactory
    hostname: satisfactory
    image: ghcr.io/wolveix/satisfactory-server:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 7777:7777/tcp
      - 7777:7777/udp
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=UTC
      - PGID=999
      - PUID=999
      - MAXPLAYERS=16
      - STEAMBETA=false
      - SERVERIP=
      # - ROOTLESS=true
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
```
