### ISSUE TITLE
Container stop does not save the game progress

### ISSUE THREAD

**Issue by DenuxPlays** [wolveix/satisfactory-server#313]
### Describe the Bug

When the container stops it does not save the games progress.

### Your Runtime Command or Docker Compose File

```yaml
services:
  satisfactory-server:
    image: 'wolveix/satisfactory-server:latest'
    restart: unless-stopped
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './config:/config'
    environment:
      AUTOSAVENUM: 3
      MAXPLAYERS: 8
      SERVERIP: ''
      PGID: 1000
      PUID: 1000
      ROOTLESS: false
      STEAMBETA: false
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
```

### Debug Output

///

### System Specs (please complete the following information):

If you're on Linux, just paste the following block as a single command, and paste the output here.

===== START ISSUE REPORT =====
OS:  Linux winchester 6.10.7-100.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 30 00:07:39 UTC 2024 x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU D-1521 @ 2.40GHz
RAM: 18GB/31GB
HDD: 112GB/445GB (26% used)
===== END ISSUE REPORT =====

### Logs

///

### Additional Context

It isn't a bug just a missing feature.
