### ISSUE TITLE
It doesn't appear to ever turn night

### ISSUE THREAD

**Issue by TheDutchMC** [wolveix/satisfactory-server#32]
**Describe the Bug**
The game never turns to night, it always stays day.

**Your Runtime Command or Docker Compose File**
```yaml
version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    environment:
    - STEAMUSER=[...]
    - STEAMPWD=[...]
    - STEAMCODE=[...]
    - MAXBACKUPS=10
    ports:
    - '7777:7777/udp'
    volumes:
    - './config:/config'
    restart: unless-stopped
```
**System Specs (please complete the following information):**
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Additional Context**
N.A
