### ISSUE TITLE
Any information about memory usage ?

### ISSUE THREAD

**Issue by Jeoffreybauvin** [wolveix/satisfactory-server#33]
Hello,

I think I know the answer... Do you have some informations about memory consumption ?

My host :

```
root@srv:# free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi        12Gi       1.4Gi       7.0Mi       2.0Gi       3.5Gi
Swap:         2.0Gi       290Mi       1.7Gi
```

My containers : 

```
root@srv:# docker stats
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O         PIDS
f41052af0c31   satis-2   127.76%   6.015GiB / 7.906GiB   76.09%    133MB / 49.2MB   35.3GB / 10.2GB   91
ef84a28a082b   satis-1   133.39%   7.318GiB / 7.906GiB   92.56%    352MB / 232MB    35.4GB / 10.6GB   91
```

They are using each half of the memory available on the host, and no one on the servers for several days...

Regards,

**Comment by wolveix** [comment]
I believe the implementation of the official dedicated server resolved the nemory usage issues. Please feel free to reopen this if the issue arises again :)

**Comment by thewinger** [comment]
Hello,
I am seeing this happening to me.
Created the server 2 weeks ago and the container is always at 5-10% CPU and 4-5G of Memory Usage, even when no one is connected.
![image](https://user-images.githubusercontent.com/121455/148735741-6bba7fbf-9ad4-48cc-9e14-dcf120bd9c8c.png)

Docker-compose:
```
satisfactory:
    container_name: satisfactory
    hostname: satisfactory
    image: wolveix/satisfactory-server:latest
    restart: unless-stopped
    networks:
        - t2_proxy
    ports:
        - '7777:7777/udp'
        - '15000:15000/udp'
        - '15778:15777/udp'
    volumes:
        - $DOCKERDIR/satisfactory:/config
    environment:
        - MAXPLAYERS=4
        - PUID=$PUID
        - PGID=$PGID
        - STEAMBETA=false
        - DISABLESEASONALEVENTS=true
        - AUTOPAUSE=true
```
