### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by patvdleer** [wolveix/satisfactory-server#343]
> I realize this may not belong here but I wanted to be sure it's not a config issue.

### Describe the Bug

Horrible lag in specific places, mainly in the east of the map, using the train and while driving the explorer. Hovering over the middle, the pink/red parts also causes the lag but its gone as soon as I'm out of there.

For some reason my ping goes up from ~ 15ms to > 500ms... 

Since the lag seems to come and the CPU and MEM isn't going apeshit I'm guessing it's not a hardware issue.

I've tried upping the network quality in game to ultra and even the rates in the `FactoryGame/Saved/Config/LinuxServer/Engine.ini` but doesn't seem to help.

```ini
[/Script/OnlineSubsystemUtils.IpNetDriver]
MaxClientRate=3000000
MaxInternetClientRate=3000000

....

[/Script/Engine.Player]
ConfiguredInternetSpeed=3000000
ConfiguredLanSpeed=3400000

[/Script/SteamSockets.SteamSocketsNetDriver]
MaxClientRate=3000000
MaxInternetClientRate=3000000

[/Script/SocketSubsystemEOS.NetDriverEOSBase]
MaxClientRate=3000000
MaxInternetClientRate=3000000

[/Script/FactoryGame.FGGameEngine]
GlobalNetTravelCount=4
```

### Your Runtime Command or Docker Compose File

```yaml
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './data:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS='false'
      - STEAMBETA='false'
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 8G
#        reservations:
#          memory: 4G
```

### Debug Output

[debug.log](https://github.com/user-attachments/files/17138649/debug.log)

### System Specs (please complete the following information):

```shell
===== START ISSUE REPORT =====
OS:  Linux fractal 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i3-7100T CPU @ 3.40GHz
RAM: 14GB/31GB
HDD: 162GB/458GB (38% used)
===== END ISSUE REPORT =====
```

### Logs

[logs.log](https://github.com/user-attachments/files/17145801/logs.log)

Notice the `LogNetPlayerMovement`, this was when I was roaming around the map while playing alone...

`satisfactory-server    | [2024.09.26-09.03.53:580][996]LogNetPlayerMovement: Warning: ServerMove: TimeStamp expired: 23.949320, CurrentTimeStamp: 25.450558, Character: Char_Player_C_2147476832`
