### ISSUE TITLE
Boot Loop with Error! App '1690800' state is 0x606 after update job.

### ISSUE THREAD

**Issue by jsleep** [wolveix/satisfactory-server#359]
### Describe the Bug

Friends needed wanted me to update the server, so I added "docker compose pull" to my VM bootscript. Now upon rebooting and starting the docker image it runs into a boot loop below printing the following logs:

satisfactory-server  | IPC function call IClientAppManager::GetUpdateInfo took too long: 235 msec
satisfactory-server  |  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
satisfactory-server  |  Update state (0x11) preallocating, progress: 25.31 (317223411 / 1253435258)
satisfactory-server  |  Update state (0x11) preallocating, progress: 25.31 (317228183 / 1253435258)
satisfactory-server  |  Update state (0x11) preallocating, progress: 25.31 (317233573 / 1253435258)
satisfactory-server  |  Update state (0x61) downloading, progress: 0.00 (0 / 1253435258)
satisfactory-server  | IPC function call IClientAppManager::GetUpdateInfo took too long: 53 msec
satisfactory-server  | Error! App '1690800' state is 0x606 after update job.

### Your Runtime Command or Docker Compose File

default docker compose in README, other than increased timeout to 60 to see if it would help:

```yaml
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/mnt/satisfactory:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - TIMEOUT=60
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
```

### Debug Output

Run the container with `DEBUG=true` as an environment variable, and it'll print out the system specs requested below, as
well as a bunch of information about your container (version, environment variables, etc.)

```shell
satisfactory-server  | System info:
satisfactory-server  | OS:  Linux satisfactory-server 6.8.0-1014-azure #16~22.04.1-Ubuntu SMP Thu Aug 15 21:31:41 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
satisfactory-server  | CPU: AMD EPYC 7763 64-Core Processor
satisfactory-server  | RAM: 7GB/7GB
satisfactory-server  | HDD: 5GB/29GB (18% used)
satisfactory-server  |
satisfactory-server  | Current version:
satisfactory-server  | 1.8.7
satisfactory-server  | Current user:
satisfactory-server  | uid=0(root) gid=0(root) groups=0(root)
satisfactory-server  | Proposed user:
satisfactory-server  | uid=1000(?) gid=1000(?) groups=1000(?)
satisfactory-server  |
satisfactory-server  | Exiting...
```

### System Specs (please complete the following information):

If you're on Linux, just paste the following block as a single command, and paste the output here.

```shell
===== START ISSUE REPORT =====
OS:  Linux satisfactoryvm 6.8.0-1014-azure #16~22.04.1-Ubuntu SMP Thu Aug 15 21:31:41 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD EPYC 7763 64-Core Processor
RAM: 7GB/7GB
HDD: 5GB/29GB (18% used)
===== END ISSUE REPORT =====
```

### Logs

Let me know any other logs that would help here other than that provided above.

### Additional Context

Running on an azure VM with 8GB ram, mounted with SSD fileshare that still seems to work for R/W directly from VM...
