### ISSUE TITLE
getting "crontab:command not found"

### ISSUE THREAD

**Issue by LoganAvatar** [wolveix/satisfactory-server#36]
using docker compose

```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:dev'
        environment:
            - MAXBACKUPS=10
            - STEAMBETA=true
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/path/to/config:/config'
        restart: unless-stopped

```

and running docker compose with
`docker compose -f satisfactory.yaml up -d`

results in this in the logs:
`/init.sh: line 31: crontab: command not found`

https://github.com/wolveix/satisfactory-server/blob/fa271822e90086d01e3a1533eb5b9d5a333d5653/init.sh#L31
