### ISSUE TITLE
Error! App '1690800' state is 0x6 after update job.

### ISSUE THREAD

**Issue by Obscured84** [wolveix/satisfactory-server#371]
Hi guys, just tried to update today

seems something is going wrong

some part of the log:

```
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
IPC function call IClientAppManager::GetUpdateInfo took too long: 90 msec
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '1690800' state is 0x6 after update job.

```

compose file:

```
services:
  satisfactory:
    restart: unless-stopped
    container_name: satisfactory
    image: wolveix/satisfactory-server:latest
    ports:
      - '7777:7777/tcp'
      - '7777:7777/udp'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/obscured/satisfactory:/config
    environment:
      PUID: '1000'
      PGID: '1000'
      MAXPLAYERS: '4'
      STEAMBETA: 'false'
      AUTOPAUSE: 'false'
      AUTOSAVEINTERVAL: 1800
      AUTOSAVENUM: 48
      AUTOSAVEONDISCONNECT: 'true'
      CRASHREPORT: 'true'
      MAXOBJECTS: 2162688
      MAXTICKRATE: 60
      NETWORKQUALITY: 3
      SKIPUPDATE: 'false'
      ROOTLESS: 'false'
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G
```
