### ISSUE TITLE
SteamCMD download error

### ISSUE THREAD

**Issue by voruti** [wolveix/satisfactory-server#389]
The game won't start (see logs below).

### Docker Compose File

```yml
name: satisfactory
services:
  satisfactory:
    deploy:
      resources:
        limits:
          memory: "17179869184"
        reservations:
          memory: "4294967296"
    environment:
      AUTOPAUSE: "false"
      AUTOSAVEINTERVAL: "1200"
      MAXPLAYERS: "4"
      PGID: "1000"
      PUID: "1000"
      ROOTLESS: "true"
      STEAMBETA: "false"
      TIMEOUT: "60"
      TZ: Europe/Berlin
      VMOVERRIDE: "false"
    hostname: satisfactory-server
    image: wolveix/satisfactory-server:v1.9.1
    labels:
      wud.tag.include: ^v\d+\.\d+\.\d+$$
    networks:
      default: null
    ports:
      - mode: ingress
        target: 7777
        published: "7777"
        protocol: udp
      - mode: ingress
        target: 7777
        published: "7777"
        protocol: tcp
    restart: always
    user: 1000:1000
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /home/user/composefiles/gaming/satisfactory/data
        target: /config/saved
        bind:
          create_host_path: true
      - type: volume
        source: satisfactory-gamefiles
        target: /config/gamefiles
        volume: {}
networks:
  default:
    name: satisfactory_default
volumes:
  satisfactory-gamefiles:
    name: satisfactory_satisfactory-gamefiles
```

### Debug Output

```shell
satisfactory-1  | ===== Satisfactory Server 1.9.1 =====
satisfactory-1  | https://github.com/wolveix/satisfactory-server
satisfactory-1  |
satisfactory-1  | Debugging enabled (the container will exit after printing the debug info)
satisfactory-1  |
satisfactory-1  | Printing environment variables:
satisfactory-1  | declare -x AUTOPAUSE="false"
satisfactory-1  | declare -x AUTOSAVEINTERVAL="1200"
satisfactory-1  | declare -x AUTOSAVENUM="5"
satisfactory-1  | declare -x DEBIAN_FRONTEND="noninteractive"
satisfactory-1  | declare -x DEBUG="true"
satisfactory-1  | declare -x DISABLESEASONALEVENTS="false"
satisfactory-1  | declare -x GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved"
satisfactory-1  | declare -x GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
satisfactory-1  | declare -x HOME="/home/steam"
satisfactory-1  | declare -x HOSTNAME="satisfactory-server"
satisfactory-1  | declare -x LANG="en_US.UTF-8"
satisfactory-1  | declare -x LANGUAGE="en_US:en"
satisfactory-1  | declare -x LOG="false"
satisfactory-1  | declare -x MAXOBJECTS="2162688"
satisfactory-1  | declare -x MAXPLAYERS="4"
satisfactory-1  | declare -x MAXTICKRATE="30"
satisfactory-1  | declare -x OLDPWD
satisfactory-1  | declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
satisfactory-1  | declare -x PGID="1000"
satisfactory-1  | declare -x PUID="1000"
satisfactory-1  | declare -x PWD="/config"
satisfactory-1  | declare -x ROOTLESS="true"
satisfactory-1  | declare -x SERVERGAMEPORT="7777"
satisfactory-1  | declare -x SERVERSTREAMING="true"
satisfactory-1  | declare -x SHLVL="1"
satisfactory-1  | declare -x SKIPUPDATE="false"
satisfactory-1  | declare -x STEAMAPPID="1690800"
satisfactory-1  | declare -x STEAMBETA="false"
satisfactory-1  | declare -x TIMEOUT="60"
satisfactory-1  | declare -x TZ="Europe/Berlin"
satisfactory-1  | declare -x USER="steam"
satisfactory-1  | declare -x VERSION="1.9.1"
satisfactory-1  | declare -x VMOVERRIDE="false"
satisfactory-1  |
satisfactory-1  | System info:
satisfactory-1  | OS:  Linux satisfactory-server 6.6.71 #1-NixOS SMP PREEMPT_DYNAMIC Fri Jan 10 13:31:36 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
satisfactory-1  | CPU: 12th Gen Intel(R) Core(TM) i5-12500
satisfactory-1  | RAM: 38GB/56GB
satisfactory-1  | HDD: 152GB/295GB (54% used)
satisfactory-1  |
satisfactory-1  | Current version:
satisfactory-1  | 1.9.1
satisfactory-1  | Current user:
satisfactory-1  | uid=1000(steam) gid=1000(steam) groups=1000(steam)
satisfactory-1  | Proposed user:
satisfactory-1  | uid=1000(?) gid=1000(?) groups=1000(?)
satisfactory-1  |
satisfactory-1  | Exiting...
satisfactory-1 exited with code 1
```

### System Specs

```shell
===== START ISSUE REPORT =====
OS:  Linux hostname 6.6.71 #1-NixOS SMP PREEMPT_DYNAMIC Fri Jan 10 13:31:36 UTC 2025 x86_64 GNU/Linux
CPU: 12th Gen Intel(R) Core(TM) i5-12500
RAM: 38GB/56GB
HDD: 152GB/295GB (54% used)
===== END ISSUE REPORT =====
```

### Logs

```shell
satisfactory-1  | ===== Satisfactory Server 1.9.1 =====
satisfactory-1  | https://github.com/wolveix/satisfactory-server
satisfactory-1  |
satisfactory-1  | Checking available memory: 38GB detected
satisfactory-1  | Clearing old Satisfactory logs (set LOG=true to disable this)
satisfactory-1  | Setting autosave number to 5
satisfactory-1  | Setting max objects to 2162688
satisfactory-1  | Setting max tick rate to 30
satisfactory-1  | Setting server streaming to 1
satisfactory-1  | Setting timeout to 60
satisfactory-1  | Setting max players to 4
satisfactory-1  | Checking available storage: 129GB detected
satisfactory-1  |
satisfactory-1  | Downloading the latest version of the game...
satisfactory-1  | Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
satisfactory-1  | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
satisfactory-1  | [  0%] Checking for available update...
satisfactory-1  | KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]
satisfactory-1  |
satisfactory-1  | ../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
satisfactory-1  | [----] Verifying installation...
satisfactory-1  | [  0%] Downloading Update...
satisfactory-1  | [  0%] Checking for available update...
satisfactory-1  | KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 15]
satisfactory-1  |
satisfactory-1  | ../tier1/KeyValues.cpp (2925) : Assertion Failed: Error while parsing text KeyValues for resource manifest
satisfactory-1  | [----] !!! Fatal Error: Steamcmd needs to be online to update.         Please confirm your network connection and try again.
satisfactory-1  | threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x5782d650/0x0xf7724a'
satisfactory-1 exited with code 0
```

### Docker Version

```shell
Docker version 27.3.1, build v27.3.1
Docker Compose version 2.30.3
```

### Additional Context (/ what I already tried)

1. The error occured with Satisfactory Server image version v1.8.9 (was already running that version for a while, but did Linux system updates recently). I also tried v1.8.7 and now v1.9.1, which also don't work.
2. I tried deleting the `satisfactory-gamefiles` volume (and re-setting the owner to id 1000) - didn't help.
3. The `ping media.steampowered.com` and add to `/etc/hosts` hack didn't help.
4. I previously was on QEMU CPU and tried to fix it by switching to Proxmox type host CPU, which didn't help (logs/debug from above are collected after switching).
5. I already tried with `network_mode: host` - same result.
