### ISSUE TITLE
running `latest` container from scratch fails

### ISSUE THREAD

**Issue by LoganAvatar** [wolveix/satisfactory-server#39]
Getting the following when creating a container off the `latest` tag with the config dir bound /satisfactory/config:/config 

compose yml file:
```
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            - MAXBACKUPS=10
            - STEAMBETA=true
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/satisfactory/config:/config'
        restart: unless-stopped
```

Eventual output:
```
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.96 (43398951 / 4533684530)
 Update state (0x61) downloading, progress: 7.01 (318036485 / 4533684530)
 Update state (0x61) downloading, progress: 13.91 (630544018 / 4533684530)
 Update state (0x61) downloading, progress: 20.85 (945322758 / 4533684530)
 Update state (0x61) downloading, progress: 26.88 (1218622584 / 4533684530)
 Update state (0x61) downloading, progress: 32.76 (1485171481 / 4533684530)
 Update state (0x61) downloading, progress: 39.95 (1811217720 / 4533684530)
 Update state (0x61) downloading, progress: 46.50 (2108284929 / 4533684530)
 Update state (0x61) downloading, progress: 53.63 (2431609137 / 4533684530)
 Update state (0x61) downloading, progress: 60.52 (2743565644 / 4533684530)
 Update state (0x61) downloading, progress: 65.79 (2982875211 / 4533684530)
 Update state (0x61) downloading, progress: 70.53 (3197722989 / 4533684530)
 Update state (0x61) downloading, progress: 74.60 (3382109276 / 4533684530)
 Update state (0x61) downloading, progress: 77.25 (3502281640 / 4533684530)
 Update state (0x61) downloading, progress: 79.75 (3615523827 / 4533684530)
 Update state (0x61) downloading, progress: 81.95 (3715138335 / 4533684530)
 Update state (0x61) downloading, progress: 84.23 (3818857698 / 4533684530)
 Update state (0x61) downloading, progress: 87.10 (3948989646 / 4533684530)
 Update state (0x61) downloading, progress: 89.66 (4064696846 / 4533684530)
 Update state (0x61) downloading, progress: 92.03 (4172309220 / 4533684530)
 Update state (0x61) downloading, progress: 94.44 (4281681755 / 4533684530)
 Update state (0x61) downloading, progress: 97.35 (4413656630 / 4533684530)
 Update state (0x61) downloading, progress: 100.00 (4533684530 / 4533684530)
 Update state (0x81) verifying update, progress: 12.46 (564771475 / 4533684530)
 Update state (0x81) verifying update, progress: 25.22 (1143521065 / 4533684530)
 Update state (0x81) verifying update, progress: 38.21 (1732385193 / 4533684530)
 Update state (0x81) verifying update, progress: 51.13 (2318138702 / 4533684530)
 Update state (0x81) verifying update, progress: 64.06 (2904145943 / 4533684530)
 Update state (0x81) verifying update, progress: 76.01 (3446057136 / 4533684530)
 Update state (0x81) verifying update, progress: 89.11 (4039766544 / 4533684530)
Success! App '1690800' fully installed.
cp: target '/config/gamefiles/FactoryGame/Saved/Config/LinuxServer/' is not a directory
```
