### ISSUE TITLE
SIGFAUTL on my system docker-compose

### ISSUE THREAD

**Issue by not-alone** [wolveix/satisfactory-server#401]
[log_segfault.txt](https://github.com/user-attachments/files/18965443/log_segfault.txt)
this is log for this docker-compose file. config folder is empty before start 

```
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './config:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
#      - VMOVERRIDE=true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 10G
        reservations:
          memory: 8G

```
