### ISSUE TITLE
Healthcheck cannot be run as non-root user

### ISSUE THREAD

**Issue by barrelmaker97** [wolveix/satisfactory-server#406]
### Describe the Bug

The healthcheck script in the container has permissions that prevent it from being run if the UID/GID is not root. This means that monitoring the container health (with Kubernetes liveness/readiness probes, for example) is not possible.

### Your Runtime Command or Docker Compose File

I'm using a helm chart to deploy the server on Kubernetes. The YAML is as follows.

```yaml
---
# Source: satisfactory/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-satisfactory
  labels:
    helm.sh/chart: satisfactory-0.2.0
    app.kubernetes.io/name: satisfactory
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v1.9.5"
    app.kubernetes.io/managed-by: Helm
---
# Source: satisfactory/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-satisfactory-env
  labels:
    helm.sh/chart: satisfactory-0.2.0
    app.kubernetes.io/name: satisfactory
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v1.9.5"
    app.kubernetes.io/managed-by: Helm
data:
  AUTOPAUSE: "true"
  AUTOSAVEINTERVAL: "300"
  AUTOSAVENUM: "3"
  AUTOSAVEONDISCONNECT: "true"
  CRASHREPORT: "true"
  DEBUG: "false"
  DISABLESEASONALEVENTS: "false"
  MAXPLAYERS: "6"
  PGID: "1000"
  PUID: "1000"
  SERVERGAMEPORT: "7777"
  SERVERIP: "0.0.0.0"
  SKIPUPDATE: "false"
  STEAMBETA: "false"
---
# Source: satisfactory/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-satisfactory
  labels:
    helm.sh/chart: satisfactory-0.2.0
    app.kubernetes.io/name: satisfactory
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v1.9.5"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: satisfactory
    app.kubernetes.io/instance: test
  ports:
  - name: game-port-udp
    port: 7777
    targetPort: 7777
    protocol: UDP
  - name: game-port-tcp
    port: 7777
    targetPort: 7777
    protocol: TCP
---
# Source: satisfactory/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-satisfactory
  labels:
    helm.sh/chart: satisfactory-0.2.0
    app.kubernetes.io/name: satisfactory
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v1.9.5"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: test-satisfactory
  selector:
    matchLabels:
      app.kubernetes.io/name: satisfactory
      app.kubernetes.io/instance: test
  template:
    metadata:
      annotations:
        checksum/configmap: 1b48a3490d80a1af4a62dbd236cdab198455dc0e16974bec149bd6b7ecc125da
      labels:
        app.kubernetes.io/name: satisfactory
        app.kubernetes.io/instance: test
    spec:
      serviceAccountName: test-satisfactory
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: satisfactory
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          image: "wolveix/satisfactory-server:v1.9.5"
          imagePullPolicy: IfNotPresent
          ports:
            - name: game-port-udp
              containerPort: 7777
              protocol: UDP
            - name: game-port-tcp
              containerPort: 7777
              protocol: TCP
          envFrom:
            - configMapRef:
                name: test-satisfactory-env
          resources:
            limits:
              memory: 8000Mi
            requests:
              cpu: 1000m
              memory: 7500Mi
          volumeMounts:
            - name: savedata
              mountPath: /config
            - name: certificate
              mountPath: /config/gamefiles/FactoryGame/Certificates
              readOnly: true
      volumes:
        - name: certificate
          secret:
            secretName: test-satisfactory
            items:
              - key: tls.crt
                path: cert_chain.pem
              - key: tls.key
                path: private_key.pem
  volumeClaimTemplates:
    - metadata:
        name: savedata
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
---
# Source: satisfactory/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-satisfactory
  labels:
    helm.sh/chart: satisfactory-0.2.0
    app.kubernetes.io/name: satisfactory
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "v1.9.5"
    app.kubernetes.io/managed-by: Helm
spec:
  secretName: test-satisfactory
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: satisfactory.barrelmaker.dev
  dnsNames:
    - satisfactory.barrelmaker.dev

```

### System Specs
```
===== START ISSUE REPORT =====
OS:  Linux test-satisfactory-0 6.12.18-talos #1 SMP Tue Mar 11 15:15:12 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
CPU: 13th Gen Intel(R) Core(TM) i5-1340P
RAM: 8GB/15GB
HDD: 96GB/476GB (21% used)
===== END ISSUE REPORT =====
```

### Additional Context

I didn't attach any logs/debug info since the container is running just fine, but let me know if you need them and I can collect them. The main thing I noticed is the following:
```
steam@test-satisfactory-0:/$ ls -la
total 20
drwxr-xr-x   1 root root    40 Mar 28 16:40 .
drwxr-xr-x   1 root root    40 Mar 28 16:40 ..
lrwxrwxrwx   1 root root     7 Sep 11  2024 bin -> usr/bin
drwxr-xr-x   2 root root     6 Apr 18  2022 boot
drwxrwsr-x   7 root steam 4096 Mar 28 16:40 config
drwxr-xr-x   5 root root   340 Mar 28 16:40 dev
drwxr-xr-x   1 root root  4096 Jan 24 22:40 etc
-rw-r--r--   1 root root   240 Jan 24 22:40 healthcheck.sh
drwxr-xr-x   1 root root    19 Jan 24 22:40 home
-rwxr-xr-x   1 root root  4810 Jan 24 22:40 init.sh
lrwxrwxrwx   1 root root     7 Sep 11  2024 lib -> usr/lib
lrwxrwxrwx   1 root root     9 Sep 11  2024 lib32 -> usr/lib32
lrwxrwxrwx   1 root root     9 Sep 11  2024 lib64 -> usr/lib64
lrwxrwxrwx   1 root root    10 Sep 11  2024 libx32 -> usr/libx32
drwxr-xr-x   2 root root     6 Sep 11  2024 media
drwxr-xr-x   2 root root     6 Sep 11  2024 mnt
drwxr-xr-x   2 root root     6 Sep 11  2024 opt
dr-xr-xr-x 502 root root     0 Mar 28 16:40 proc
drwx------   1 root root    34 Jan 24 05:20 root
drwxr-xr-x   1 root root    21 Mar 28 16:40 run
lrwxrwxrwx   1 root root     8 Sep 11  2024 sbin -> usr/sbin
drwxr-xr-x   2 root root     6 Sep 11  2024 srv
dr-xr-xr-x  13 root root     0 Mar 28 16:40 sys
drwxrwxrwt   1 root root    57 Mar 28 16:41 tmp
drwxr-xr-x   1 root root    53 Sep 11  2024 usr
drwxr-xr-x   1 root root    41 Sep 11  2024 var
steam@test-satisfactory-0:/$ ./healthcheck.sh
bash: ./healthcheck.sh: Permission denied
```
The owner/group of the healthcheck script is root and the permissions are such that the Steam user (1000:1000) cannot run it. I want to add liveness/readiness probes to my deployment, so having the script available would be really handy.
