### ISSUE TITLE
When using custom server ports, the docker container seems to still expose the default ports.

### ISSUE THREAD

**Issue by mikedevita** [wolveix/satisfactory-server#420]
### Describe the Bug
I'm running a dedicated satisfactory server through pterodactyl panel which uses the default ports. I want to spin up a second server, using your image but run it under non default port `7778`

When I launch the second server using your image, it seems to still expose port `7777` and `8888` which is causing a port conflict with my other server.

![Image](https://github.com/user-attachments/assets/e3915576-18aa-4f84-a91c-7afc41ba12c8)

### Your Runtime Command or Docker Compose File

```yaml
services:
  satisfactory-server:
    image: wolveix/satisfactory-server:latest
    container_name: boost-satis-server
    restart: unless-stopped
    environment:
      MAXPLAYERS: 4
      PGID: 1002
      PUID: 1002
      AUTOSAVENUM: 5
      DEBUG: false
      DISABLESEASONALEVENTS: false
      LOG: true
      MAXOBJECTS: 2162688
      MAXTICKRATE: 30
      SERVERGAMEPORT: 7778
      SERVERMESSAGINGPORT: 8889
      SERVERSTREAMING: true
      SKIPUPDATE: false
      STEAMBETA: true
      TIMEOUT: 30
      VMOVERRIDE: false
    ports:
      - "7778:7778/udp"
      - "7778:7778/tcp"
    volumes:
      - ./data:/config
```

### Debug Output
```shell
boost-satis-server  | ===== Satisfactory Server 1.9.8 =====
boost-satis-server  | https://github.com/wolveix/satisfactory-server
boost-satis-server  |
boost-satis-server  | Debugging enabled (the container will exit after printing the debug info)
boost-satis-server  |
boost-satis-server  | Printing environment variables:
boost-satis-server  | declare -x AUTOSAVENUM="5"
boost-satis-server  | declare -x CURRENTGID="0"
boost-satis-server  | declare -x CURRENTUID="0"
boost-satis-server  | declare -x DEBIAN_FRONTEND="noninteractive"
boost-satis-server  | declare -x DEBUG="true"
boost-satis-server  | declare -x DISABLESEASONALEVENTS="false"
boost-satis-server  | declare -x GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved"
boost-satis-server  | declare -x GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
boost-satis-server  | declare -x HOME="/home/steam"
boost-satis-server  | declare -x HOSTNAME="990a9ca462f2"
boost-satis-server  | declare -x LANG="en_US.UTF-8"
boost-satis-server  | declare -x LANGUAGE="en_US:en"
boost-satis-server  | declare -x LOG="false"
boost-satis-server  | declare -x MAXOBJECTS="2162688"
boost-satis-server  | declare -x MAXPLAYERS="4"
boost-satis-server  | declare -x MAXTICKRATE="30"
boost-satis-server  | declare -x MULTIHOME="::"
boost-satis-server  | declare -x OLDPWD
boost-satis-server  | declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
boost-satis-server  | declare -x PGID="1002"
boost-satis-server  | declare -x PUID="1002"
boost-satis-server  | declare -x PWD="/config"
boost-satis-server  | declare -x SERVERGAMEPORT="7778"
boost-satis-server  | declare -x SERVERMESSAGINGPORT="8889"
boost-satis-server  | declare -x SERVERSTREAMING="true"
boost-satis-server  | declare -x SHLVL="1"
boost-satis-server  | declare -x SKIPUPDATE="false"
boost-satis-server  | declare -x STEAMAPPID="1690800"
boost-satis-server  | declare -x STEAMBETA="true"
boost-satis-server  | declare -x STEAMGID="1000"
boost-satis-server  | declare -x STEAMUID="1000"
boost-satis-server  | declare -x TIMEOUT="30"
boost-satis-server  | declare -x USER="steam"
boost-satis-server  | declare -x VERSION="1.9.8"
boost-satis-server  | declare -x VMOVERRIDE="false"
boost-satis-server  |
boost-satis-server  | System info:
boost-satis-server  | OS:  Linux 990a9ca462f2 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
boost-satis-server  | CPU: AMD EPYC 4584PX 16-Core Processor
boost-satis-server  | RAM: 108GB/128GB
boost-satis-server  | HDD: 23GB/878GB (3% used)
boost-satis-server  |
boost-satis-server  | Current version:
boost-satis-server  | 1.9.8
boost-satis-server  | Current user:
boost-satis-server  | uid=0(root) gid=0(root) groups=0(root)
boost-satis-server  | Proposed user:
boost-satis-server  | uid=1002(?) gid=1002(?) groups=1002(?)
boost-satis-server  |
boost-satis-server  | Exiting...
boost-satis-server exited with code 1
```

### System Specs (please complete the following information):
```
===== START ISSUE REPORT =====
OS:  Linux dedi 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD EPYC 4584PX 16-Core Processor
BIOS AMD EPYC 4584PX 16-Core Processor               Unknown CPU @ 4.2GHz
RAM: 108GB/128GB
HDD: 23GB/878GB (3% used)
===== END ISSUE REPORT =====
```

### Logs
[satisfactory-path.txt](https://github.com/user-attachments/files/20543236/satisfactory-path.txt)
[appinfo_log.txt](https://github.com/user-attachments/files/20543239/appinfo_log.txt)
[bootstrap_log.txt](https://github.com/user-attachments/files/20543242/bootstrap_log.txt)
[compat_log.txt](https://github.com/user-attachments/files/20543245/compat_log.txt)
[configstore_log.txt](https://github.com/user-attachments/files/20543237/configstore_log.txt)
[connection_log.txt](https://github.com/user-attachments/files/20543241/connection_log.txt)
[content_log.txt](https://github.com/user-attachments/files/20543240/content_log.txt)
[shader_log.txt](https://github.com/user-attachments/files/20543244/shader_log.txt)
[sitelicense_steamcmd.txt](https://github.com/user-attachments/files/20543238/sitelicense_steamcmd.txt)
[stderr.txt](https://github.com/user-attachments/files/20543243/stderr.txt)
[workshop_log.txt](https://github.com/user-attachments/files/20543246/workshop_log.txt)
