### ISSUE TITLE
Unable to set server messaging port

### ISSUE THREAD

**Issue by msubrosa** [wolveix/satisfactory-server#423]
First off, thank you for the great work in maintaining this container.

After the 1.1 update, I went about updating my server instances (there are multiple) running in different containers. These servers don't use the default ports. The first server instance has been assigned the default of 8888 for the `SERVERMESSAGINGPORT` and this works no problem. However, another instance attempts to use port 8889 but the server log does not show the change taking effect.

Port forwarding has already been set up for all ports.

My Docker compose file:
```
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'somehost.net'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '51000:51000/udp'
      - '51000:51000/tcp'
      - '8889:8889/tcp'
    volumes:
      - '/home/player/satisfactory-server:/config'
    env_file:
      - satisfactory.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
```

`satisfactory.env` file:
```
MAXPLAYERS=4
PGID=1000
UID=1000
STEAMBETA=false
SERVERGAMEPORT=51000
SERVERMESSAGINGPORT=8889
```

GREP of the server logs:
```
docker logs satisfactory-server | grep ReliableMessaging
steamcmd.sh[43]: Restarting steamcmd by request...
Project file not found: /config/gamefiles/FactoryGame/FactoryGame.uproject
LogPluginManager: Mounting Project plugin ReliableMessaging
[2025.06.10-18.15.51:340][  0]LogReliableMessaging: Server streaming socket bound to port 8888
[2025.06.10-18.15.51:340][  0]LogReliableMessaging: No port remapping specified. Clients will attempt to connect to the bound port as is.
```

I get stuck at the connection screen for this instance and the log suggests the server is not binding to the requested `SERVERMESSAGINGPORT=8889`.

Is there a way to confirm if this is being set correctly by the environment variable?

I appreciate any help/advice!
