### ISSUE TITLE
Unable to set server messaging port to custom value

### ISSUE THREAD

**Issue by msubrosa** [wolveix/satisfactory-server#424]
### Describe the Bug

Follow up from [Issue #423](https://github.com/wolveix/satisfactory-server/issues/423)

Setting the server messaging port via the `SERVERMESSAGINGPORT` environment variable does not appear to be applied to the server process.

### Your Runtime Command or Docker Compose File

```shell
docker compose up -d
```

docker-compose.yaml
```
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'somehost.net'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '51000:51000/udp'
      - '51000:51000/tcp'
      - '8889:8889/tcp'
    volumes:
      - '/home/player/satisfactory-server:/config'
    env_file:
      - satisfactory.env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 16G
```

satisfactory.env
```
MAXPLAYERS=2
PGID=1000
UID=1000
STEAMBETA=false
SERVERGAMEPORT=51000
SERVERMESSAGINGPORT=8889
```

### Debug Output

```shell
===== Satisfactory Server 1.9.5 =====
https://github.com/wolveix/satisfactory-server

Debugging enabled (the container will exit after printing the debug info)

Printing environment variables:
declare -x AUTOSAVENUM="5"
declare -x CURRENTGID="0"
declare -x CURRENTUID="0"
declare -x DEBIAN_FRONTEND="noninteractive"
declare -x DEBUG="true"
declare -x DISABLESEASONALEVENTS="false"
declare -x GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved"
declare -x GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
declare -x HOME="/home/steam"
declare -x HOSTNAME="somehost.net"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US:en"
declare -x LOG="false"
declare -x MAXOBJECTS="2162688"
declare -x MAXPLAYERS="2"
declare -x MAXTICKRATE="30"
declare -x MULTIHOME="::"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PGID="1000"
declare -x PUID="1000"
declare -x PWD="/config"
declare -x SERVERGAMEPORT="51000"
declare -x SERVERMESSAGINGPORT="8889"
declare -x SERVERSTREAMING="true"
declare -x SHLVL="1"
declare -x SKIPUPDATE="false"
declare -x STEAMAPPID="1690800"
declare -x STEAMBETA="false"
declare -x STEAMGID="1000"
declare -x STEAMUID="1000"
declare -x TIMEOUT="30"
declare -x UID="1000"
declare -x USER="steam"
declare -x VERSION="1.9.5"
declare -x VMOVERRIDE="false"

System info:
OS:  Linux somehost.net 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
CPU: 13th Gen Intel(R) Core(TM) i7-1360P
RAM: 60GB/63GB
HDD: 308GB/937GB (35% used)

Current version:
1.9.5
Current user:
uid=0(root) gid=0(root) groups=0(root)
Proposed user:
uid=1000(?) gid=1000(?) groups=1000(?)

Exiting...
```

### System Specs:

```shell
===== START ISSUE REPORT =====
OS:  Linux some-server 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
CPU: 13th Gen Intel(R) Core(TM) i7-1360P
RAM: 59GB/63GB
HDD: 308GB/937GB (35% used)
===== END ISSUE REPORT =====
```

### Logs

[satisfactory_logs.txt](https://github.com/user-attachments/files/20681179/satisfactory_logs.txt)

### Additional Context

This is a multi-instance environment and the default ports can't be used for all servers. When using the default port of 8888, the connection works, When specifying an alternative port, it does not and the server logs appear to suggest it is still binding to 8888 for reliable messaging: 
`LogReliableMessaging: Server streaming socket bound to port 8888`
