### ISSUE TITLE
"This server is unclaimed" every time I restart the container

### ISSUE THREAD

**Issue by mythmon** [wolveix/satisfactory-server#57]
Thanks for maintaining this image!

**Describe the Bug**
Every time I restart the container (such as with `docker-compose restart`), the server becomes unclaimed, and I have to create a game again. My save files are available, if I type the right session name I can get back into the same save. It also prompts for a new admin password each time.

**Your Runtime Command or Docker Compose File**

```yaml
version: "3"
services:
  satisfactory-server:
    image: wolveix/satisfactory-server:latest
    ports:
      - 7777:7777/udp # game port
      - 15000:15000/udp # beaccon port
      - 15777:15777/udp # server query port
    volumes:
      - satisfactory-data:/config
      # I realize this isn't exactly supported, but it works for me
      - ./saves:/home/steam/.config/Epic/FactoryGame/Saved/SaveGames/server
    restart: unless-stoppedversion: "3"

  # The problem happens with or without this backup service, but including it here for completeness.
  backups:
    image: southclaws/restic-robot
    hostname: fungeon-satisfactory-backups
    depends_on:
      - satisfactory-server
    volumes:
      - ./saves:/data:ro
      - ./backups:/backups:rw
      - ./backups-cleanup.sh:/backups-cleanup.sh:ro
    env_file:
      - ./secrets.env
    environment:
      SCHEDULE: "0 */15 * * *" # every 15 minute
      RESTIC_REPOSITORY: /backups
      RESTIC_ARGS: /data
      PRUNE_RESTIC_RETENTION: >
        --keep-within 48h
        --keep-daily 7
        --keep-weekly 4
        --keep-monthly 12
      POST_COMMAND: /backups-cleanup.sh
      # Set these in secrets.env
      # RESTIC_PASSWORD:

volumes:
  satisfactory-data:
```

**System Specs (please complete the following information):**
```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
```
