### ISSUE TITLE
Schedule documentation ?

### ISSUE THREAD

**Issue by Jeoffreybauvin** [wolveix/satisfactory-server#67]
Again, thanks for this image, it's working fine !

**Describe the Bug**

Just a question. in #57, I saw this environment variable : 

` SCHEDULE: "0 */15 * * *" # every 15 minute`

Is it really implemented ? Or do I need to restart manually the container everyday ?

**Your Runtime Command or Docker Compose File**

```
version: '3'
services:
    satis-1:
        container_name: 'satis-1'
        hostname: 'satis-1'
        image: 'wolveix/satisfactory-server:latest'
        environment:
            STEAMBETA: "true"
            MAXPLAYERS: "4"
            SKIPUPDATE: "false"
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/satisfactoryserveur/config/gamefiles:/config/gamefiles'
            - '/home/satisfactoryserveur/config/server1/saves:/config/saves'
            - '/home/satisfactoryserveur/config/server1/backups:/config/backups'
        restart: unless-stopped
```

**System Specs (please complete the following information):**
 - OS: Debian 10.11
 

**Additional Context**
