### ISSUE TITLE
Long Connection Times for Clients

### ISSUE THREAD

**Issue by Joinatic** [wolveix/satisfactory-server#7]
Hi there,

we got huge connection times. We need 20+ minutes to connect. All of us made the game.ini etc. changes. The container is running on an 10 core 48GB RAM V-Server. 

docker-compose
```
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    environment:
        - STEAMUSER=***
        - STEAMPWD=***
        - STEAMCODE=***
    ports:
        - '7777:7777/udp'
    volumes:
        - '/var/docker/satisfactory/config/savefilebackups:/config/savefilebackups'
        - '/var/docker/satisfactory/config/savefiles:/config/savefiles'
        - '/var/docker/satisfactory/config/steam:/config/steam'
    restart: unless-stopped
```

is it a bug or did I miss any configuration? Removed gamefiles from volumes to be sure its not an sync problem.
