### ISSUE TITLE
Clients can't connect (v5) due to "Version mismatch detected between game and server"

### ISSUE THREAD

**Issue by jp495** [wolveix/satisfactory-server#87]
```log
Version mismatch detected between game and server. Game Version: 172651, Server Version: 172183
```

I'm not sure why this seems to be running so far behind the version my friends are running (v5 Experimental). Based on what I see in the container logs I assume it's using the latest version, but I can't figure out why friends see this error when they try to join.

Any thoughts? (I'm super new to Artifactory -- I'm just hosting this for friends)

Log snippets that seemed potentially relevant:
```log
Setting max players to 8
Experimental flag is set. Experimental will be downloaded instead of Early Access.
Checking available space...169GB detected
Downloading the latest version of the game...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (76 of 54,186 KB)...
[  0%] Downloading update (3,609 of 54,186 KB)...
. . .
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
. . .
[2021.11.17-04.46.38:480][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.11.17-04.46.38:480][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.11.17-04.46.38:480][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
. . .
[2021.11.17-04.46.38:482][  0]LogInit: OnPostEngineInit has been broadcasted successfully.
[2021.11.17-04.46.38:484][  0]LogInit: Display: Starting Game.
```

`docker-compose.yml`:
```yaml
version: '3'
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '15000:15000/udp'
      - '15777:15777/udp'
    volumes:
      - '/docker-volumes/satisfactory_server:/config'
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - STEAMBETA=true  # Runs experimental branch if `true`
      - SERVERBEACONPORT=15000
      - SERVERGAMEPORT=7777
      - SERVERIP=0.0.0.0
      - SERVERQUERYPORT=15777
    restart: unless-stopped
```
